"""Defect classes PRISM knows how to look for.

COVERED = some instrument reaches PROVES or FINDS.
PARTIAL = best available is SOME or READS.
GAP     = nothing sees it.

The LLM is READS and never promotes a class to COVERED.
"""

from __future__ import annotations

from prism import laws as L

PROVES, FINDS, SOME, READS = L.STRENGTH_PROVES, L.STRENGTH_FINDS, L.STRENGTH_SOME, L.STRENGTH_READS

CLASSES: list[dict] = [
    dict(id="MEM-OOB-READ", name="out-of-bounds read", cwe=[125],
         seen={"bmc": PROVES, "esbmc": PROVES, "fuzz": FINDS, "concolic": FINDS, "cppcheck": FINDS, "lints": SOME}),
    dict(id="MEM-OOB-WRITE", name="out-of-bounds write", cwe=[787],
         seen={"bmc": PROVES, "esbmc": PROVES, "fuzz": FINDS, "concolic": FINDS, "cppcheck": FINDS}),
    dict(id="PTR-NULL-DEREF", name="null pointer dereference", cwe=[476],
         seen={"bmc": PROVES, "lints": SOME, "cppcheck": FINDS, "fuzz": FINDS}),
    dict(id="PTR-UNCHECKED-ALLOC", name="unchecked allocation", cwe=[690],
         seen={"lints": FINDS, "cppcheck": FINDS}),
    dict(id="MEM-UAF", name="use after free", cwe=[416],
         seen={"lints": FINDS, "cppcheck": FINDS, "infer": FINDS}),
    dict(id="MEM-DOUBLE-FREE", name="double free", cwe=[415],
         seen={"lints": FINDS, "cppcheck": FINDS, "infer": FINDS}),
    dict(id="FMT-STRING", name="format string from non-literal", cwe=[134],
         seen={"lints": FINDS, "taint": FINDS, "semgrep": FINDS}),
    dict(id="UNINIT-READ", name="uninitialised value", cwe=[457],
         seen={"bmc": SOME, "pir": PROVES, "cppcheck": FINDS, "lints": SOME}),
    dict(id="UNINIT-SWITCH", name="masked switch gap escapes uninit", cwe=[],
         seen={"lints": FINDS}),
    dict(id="INT-SIGNED-OVF", name="signed overflow", cwe=[190],
         seen={"bmc": PROVES, "pir": PROVES, "fuzz": FINDS, "concolic": FINDS, "esbmc": PROVES}),
    dict(id="INT-DIV-ZERO", name="division by zero", cwe=[369],
         seen={"bmc": PROVES, "pir": PROVES, "lints": SOME, "fuzz": FINDS, "concolic": FINDS, "cppcheck": FINDS}),
    dict(id="INT-SHIFT-UB", name="undefined shift", cwe=[1335],
         seen={"bmc": PROVES, "pir": PROVES, "lints": FINDS, "cppcheck": FINDS, "fuzz": FINDS, "concolic": FINDS}),
    dict(id="LOCK-IMBALANCE", name="lock released on some paths only", cwe=[],
         seen={"lints": FINDS}),
    dict(id="LOCK-ORDER", name="conflicting lock acquisition order", cwe=[833],
         seen={"lints": FINDS}),
    dict(id="LOCK-DOUBLE-UNLOCK", name="lock released twice without acquire", cwe=[765],
         seen={"lints": FINDS}),
    dict(id="LOCK-DOUBLE-LOCK", name="lock acquired twice without release", cwe=[764],
         seen={"lints": FINDS}),
    dict(id="LOCK-MISSING-INIT", name="local mutex locked without init", cwe=[456, 667],
         seen={"lints": FINDS}),
    dict(id="CXX-VIRTUAL-IN-CTOR", name="virtual call from constructor", cwe=[665],
         seen={"lints": FINDS}),
    dict(id="CXX-SLICING", name="derived object passed by value as base", cwe=[704],
         seen={"lints": FINDS}),
    dict(id="CONC-TOCTOU", name="check-then-use race on path", cwe=[367],
         seen={"lints": FINDS}),
    dict(id="CONC-ATOMICITY", name="non-atomic increment of shared global", cwe=[362, 667],
         seen={"lints": FINDS, "thread": SOME}),
    dict(id="CONC-DATA-RACE", name="data race: conflicting unordered accesses by two threads", cwe=[362],
         seen={"conc": FINDS}),
    dict(id="CONC-DEADLOCK", name="deadlock: every live thread blocked", cwe=[833],
         seen={"conc": FINDS}),
    dict(id="CXX-EXCEPTION-LEAK", name="heap allocation not deleted before throwing call", cwe=[401],
         seen={"lints": FINDS}),
    dict(id="CXX-THROW-DESTRUCTOR", name="destructor throws", cwe=[248],
         seen={"lints": FINDS}),
    dict(id="CXX-THROW-SPEC", name="dynamic exception specification", cwe=[248],
         seen={"lints": FINDS}),
    dict(id="MEM-REALLOC-SELF", name="realloc into own pointer", cwe=[401],
         seen={"lints": FINDS}),
    dict(id="MEM-REALLOC-ZERO", name="use after realloc(ptr, 0)", cwe=[761, 416],
         seen={"lints": FINDS}),
    dict(id="MEM-ONESIDED-INDEX", name="signed index bounded above only", cwe=[125, 787],
         seen={"lints": FINDS, "pbsd": FINDS}),
    dict(id="MEM-CAPACITY-FIRST", name="capacity grown before allocation earns it", cwe=[401, 680],
         seen={"lints": FINDS, "pbsd": FINDS}),
    dict(id="MEM-OVERLAP", name="memcpy with identical source and destination", cwe=[628],
         seen={"lints": FINDS}),
    dict(id="FUNC-NORETURN", name="fatal helper not marked noreturn", cwe=[],
         seen={"lints": FINDS}),
    dict(id="MEM-NOWAIT", name="M_NOWAIT allocation without NULL test", cwe=[690],
         seen={"lints": FINDS}),
    dict(id="MEM-MEMSET-SWAP", name="memset fill/size arguments swapped", cwe=[665],
         seen={"lints": FINDS, "spatch": FINDS}),
    dict(id="INT-TAUTOLOGY", name="tautological index bound (|| instead of &&)", cwe=[571],
         seen={"lints": FINDS, "spatch": FINDS}),
    dict(id="INT-BOOL-AS-BIT", name="bitwise operator on a comparison", cwe=[480],
         seen={"lints": FINDS}),
    dict(id="INT-WRAP-ALLOC", name="allocation size is a wrapping multiply", cwe=[190, 680],
         seen={"lints": FINDS}),
    dict(id="INT-TRUNC", name="narrowing integer conversion", cwe=[197],
         seen={"lints": FINDS}),
    dict(id="INT-SIGN-CONV", name="signed vs unsigned comparison", cwe=[195],
         seen={"lints": FINDS}),
    dict(id="MEM-NEW-DELETE", name="new/delete form mismatch", cwe=[762],
         seen={"lints": FINDS}),
    dict(id="MEM-STACK-ESCAPE", name="return pointer to local stack storage", cwe=[562],
         seen={"lints": FINDS}),
    dict(id="STR-UNBOUNDED-COPY", name="unbounded string copy into local buffer", cwe=[120, 787],
         seen={"lints": FINDS}),
    dict(id="CTRL-MISSING-RETURN", name="value-returning function missing return", cwe=[],
         seen={"lints": FINDS}),
    dict(id="CTRL-FALLTHROUGH", name="switch case falls through without annotation", cwe=[],
         seen={"lints": FINDS}),
    dict(id="INT-ENUM-HOLE", name="switch on enum missing enumerators", cwe=[478],
         seen={"lints": FINDS}),
    dict(id="CTRL-DEAD-GUARD", name="unsigned compared below zero", cwe=[571],
         seen={"lints": FINDS}),
    dict(id="CTRL-EMPTY-INFINITE", name="empty infinite loop", cwe=[835],
         seen={"lints": FINDS}),
    # Clang-AST lint layer (roadmap 2.8): C++ engine only (src/prism/astlint.cpp);
    # this engine lists the classes so both taxonomy tables stay equal.
    dict(id="CTRL-ASSIGN-COND", name="assignment used as a condition", cwe=[481],
         seen={"lints": FINDS}),
    dict(id="CTRL-SELF-ASSIGN", name="variable assigned to itself", cwe=[],
         seen={"lints": FINDS}),
    dict(id="CTRL-DEAD-STORE", name="local stored and never read", cwe=[563],
         seen={"lints": FINDS}),
    dict(id="INT-DIV-TO-FLOAT", name="integer division result converted to floating point",
         cwe=[682], seen={"lints": FINDS}),
    dict(id="UNINIT-RETURN", name="return of uninitialised local", cwe=[457],
         seen={"lints": FINDS}),
    dict(id="PTR-UNINIT", name="dereference of uninitialised local pointer", cwe=[457, 824],
         seen={"lints": FINDS}),
    dict(id="UNINIT-BRANCH", name="uninitialised scalar in branch condition", cwe=[457],
         seen={"lints": FINDS}),
    dict(id="STR-OFF-BY-ONE", name="string copy leaves no room for NUL", cwe=[170],
         seen={"lints": FINDS}),
    dict(id="STR-MISSING-NUL", name="memcpy of a string literal omits the terminator", cwe=[170],
         seen={"lints": FINDS}),
    dict(id="CTRL-SIBLING-ASYMMETRY", name="integer param guarded in sibling only", cwe=[],
         seen={"lints": FINDS}),
    dict(id="API-IGNORED-ERROR", name="discarded malloc/fopen/open result", cwe=[252, 391],
         seen={"lints": FINDS}),
    dict(id="API-SCANF-UNCHECKED", name="scanf family return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-GETS", name="gets() is unbounded", cwe=[242, 120],
         seen={"lints": FINDS}),
    dict(id="API-STRTOK-REENTRANT", name="strtok() is not reentrant", cwe=[477],
         seen={"lints": FINDS}),
    dict(id="API-MKSTEMP", name="mkstemp template is a string literal", cwe=[377],
         seen={"lints": FINDS}),
    dict(id="API-TMPNAM", name="tmpnam/tempnam insecure temp path", cwe=[377],
         seen={"lints": FINDS}),
    dict(id="API-MKTEMP", name="mktemp() is an insecure temp-name API", cwe=[377],
         seen={"lints": FINDS}),
    dict(id="API-SIGNAL", name="signal() handler install; prefer sigaction", cwe=[479],
         seen={"lints": FINDS}),
    dict(id="FMT-PERCENT-N", name="printf format uses %n write-back", cwe=[685, 134],
         seen={"lints": FINDS}),
    dict(id="API-SYSTEM", name="system() with non-literal command", cwe=[78],
         seen={"lints": FINDS}),
    dict(id="API-CHROOT", name="chroot without chdir into new root", cwe=[243],
         seen={"lints": FINDS}),
    dict(id="INT-ATOI", name="atoi result used as index or size unchecked", cwe=[190, 128],
         seen={"lints": FINDS}),
    dict(id="STR-SPRINTF", name="sprintf into fixed local buffer", cwe=[120],
         seen={"lints": FINDS}),
    dict(id="RES-FD-LEAK", name="descriptor closed on some returns only", cwe=[775],
         seen={"lints": FINDS}),
    dict(id="API-GETENV-NULL", name="getenv result used without NULL test", cwe=[690, 476],
         seen={"lints": FINDS}),
    dict(id="API-STRDUP-NULL", name="strdup/strndup result used without NULL test", cwe=[690],
         seen={"lints": FINDS}),
    dict(id="MEM-SIZEOF-PTR", name="allocation or buffer size is sizeof(pointer) not pointee", cwe=[131],
         seen={"lints": FINDS}),
    dict(id="API-POPEN", name="popen stream not pclosed on every exit", cwe=[775],
         seen={"lints": FINDS}),
    dict(id="API-UMASK", name="umask(0) leaves world-writable default", cwe=[732],
         seen={"lints": FINDS}),
    dict(id="API-FORK", name="fork()/vfork() result unused", cwe=[362, 273],
         seen={"lints": FINDS}),
    dict(id="API-EXEC", name="exec* with a non-literal path", cwe=[78],
         seen={"lints": FINDS}),
    dict(id="API-MMAP", name="mmap() result used without MAP_FAILED test", cwe=[252, 119],
         seen={"lints": FINDS}),
    dict(id="STR-WCSCPY", name="unbounded wcscpy/wcscat into local wchar buffer", cwe=[120],
         seen={"lints": FINDS}),
    dict(id="API-GETCWD", name="getcwd result used without NULL test", cwe=[252, 476],
         seen={"lints": FINDS}),
    dict(id="API-IOCTL", name="ioctl() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-DLOPEN", name="dlopen() result used without NULL test", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-ACCEPT", name="accept()/accept4() result used without < 0 test", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-REALPATH", name="realpath result used without NULL test", cwe=[252, 22],
         seen={"lints": FINDS}),
    dict(id="API-CHMOD-WORLD", name="chmod/fchmod with world-writable mode 0777", cwe=[732],
         seen={"lints": FINDS}),
    dict(id="INT-CLZ-ZERO", name="__builtin_clz/ctz on 0 or an unguarded variable", cwe=[758],
         seen={"lints": FINDS, "pir": PROVES}),
    dict(id="MEM-BCOPY", name="bcopy with identical source and destination", cwe=[628],
         seen={"lints": FINDS}),
    dict(id="API-SETUID", name="setuid/seteuid/setgid to 0 without a return check", cwe=[250],
         seen={"lints": FINDS}),
    dict(id="API-SOCKET", name="socket() result used without < 0 test", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-BIND", name="bind() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="STR-SNPRINTF", name="snprintf size larger than local destination array", cwe=[120],
         seen={"lints": FINDS}),
    dict(id="API-UNLINK", name="unlink/remove return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-MKFIFO", name="mkfifo/mknod return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-LISTEN", name="listen() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-CONNECT", name="connect() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-PIPE", name="pipe()/pipe2() result used without a <0 test", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-DUP", name="dup/dup2/dup3 result used without a <0 test", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-FCNTL", name="fcntl() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-WAIT", name="wait/waitpid/waitid return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-SELECT", name="select/poll/epoll_wait return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-SEND", name="send/recv/sendto/recvfrom return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-SHUTDOWN", name="shutdown() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-KILL", name="kill/raise return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-GETADDRINFO", name="getaddrinfo result used without a ==0 test", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-PTHREAD-JOIN", name="pthread_join()/pthread_detach() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-THRD-JOIN", name="ISO C11 thrd_join()/thrd_detach() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-SEM-WAIT", name="sem_wait()/sem_post() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-OPENAT", name="openat() result used without a <0 test", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-FLOCK", name="flock() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-CHOWN", name="chown/fchown/lchown return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-SYMLINK", name="symlink()/readlink() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-OPENDIR", name="opendir() result used without a NULL test", cwe=[252, 476],
         seen={"lints": FINDS}),
    dict(id="API-SETRLIMIT", name="setrlimit()/getrlimit() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-GETSOCKOPT", name="getsockopt()/setsockopt() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-STAT", name="stat()/lstat()/fstat() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-MKDIR", name="mkdir()/rmdir() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-GETPWUID", name="getpwuid()/getpwnam() result used without a NULL test", cwe=[252, 476],
         seen={"lints": FINDS}),
    dict(id="API-CLOCK-GETTIME", name="clock_gettime()/gettimeofday() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-SHM-OPEN", name="shm_open() result used without a <0 test", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-POSIX-SPAWN", name="posix_spawn()/posix_spawnp() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-GLOB", name="glob() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-FSEEK", name="fseek()/ftell() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-ACCESS", name="access() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-GETOPT", name="getopt()/getopt_long() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-UNAME", name="uname()/gethostname() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-SENDFILE", name="sendfile()/copy_file_range() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-MEMFD", name="memfd_create() result used without a <0 test", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-PRCTL", name="prctl()/ptrace() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-TCGETATTR", name="tcgetattr()/tcsetattr() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-SYSCONF", name="sysconf()/pathconf() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-GETRUSAGE", name="getrusage() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-NFTW", name="nftw()/ftw() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-WORDEXP", name="wordexp() return discarded (not compared to 0)", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-GETLOGIN", name="getlogin()/ttyname() result used without a NULL test", cwe=[252, 476],
         seen={"lints": FINDS}),
    dict(id="API-INET-PTON", name="inet_pton()/inet_aton() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-MLOCK", name="mlock()/munlock() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-SPLICE", name="splice() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-INOTIFY", name="inotify_init()/inotify_init1() result used without a <0 test", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-FSYNC", name="fsync()/fdatasync() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-GETRANDOM", name="getrandom()/getentropy() return discarded", cwe=[252, 330],
         seen={"lints": FINDS}),
    dict(id="API-GETLINE", name="getline()/getdelim() return discarded (not compared to -1)", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-ASPRINTF", name="asprintf()/vasprintf() return discarded (not compared to 0/-1)", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-STRLCPY", name="strlcpy()/strlcat() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-ISATTY", name="isatty() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-PTSNAME", name="ptsname() result used without a NULL test", cwe=[252, 476],
         seen={"lints": FINDS}),
    dict(id="API-MOUNT", name="mount()/umount() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-FMEMOPEN", name="fmemopen()/open_memstream() result used without a NULL test", cwe=[252, 476],
         seen={"lints": FINDS}),
    dict(id="API-SCANDIR", name="scandir() return discarded (not compared to <0)", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-SETXATTR", name="setxattr()/getxattr()/listxattr() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-SCHED-AFFINITY", name="sched_setaffinity()/sched_getaffinity() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-AIO", name="aio_read()/aio_write() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-STATX", name="statx() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-PIDFD", name="pidfd_open() result used without a <0 test", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-CAPSET", name="capset()/capget() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-FANOTIFY", name="fanotify_init() result used without a <0 test", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-SECCOMP", name="seccomp() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-GETGRNAM", name="getgrnam()/getgrgid()/getspnam() result used without a NULL test", cwe=[252, 476],
         seen={"lints": FINDS}),
    dict(id="API-FALLOCATE", name="posix_fallocate()/fallocate() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-CLOSE-RANGE", name="close_range() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-BPF", name="bpf() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-USERFAULTFD", name="userfaultfd() result used without a <0 test", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-GETPASS", name="getpass() result used without a NULL test", cwe=[252, 476],
         seen={"lints": FINDS}),
    dict(id="API-INITGROUPS", name="initgroups()/setgroups() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-CLONE", name="unshare()/setns()/clone() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-OPENAT2", name="openat2() result used without a <0 test", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-LANDLOCK", name="landlock_create_ruleset() result used without a <0 test", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-GETPRIORITY", name="getpriority()/setpriority() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-SIGNALFD", name="signalfd() result used without a <0 test", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-SENDMMSG", name="sendmmsg()/recvmmsg() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-PERSONALITY", name="personality() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-QUOTACTL", name="quotactl() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-NAME-TO-HANDLE", name="name_to_handle_at()/open_by_handle_at() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-PROCESS-MADVISE", name="process_madvise() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-PIVOT-ROOT", name="pivot_root() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-STATFS", name="statfs()/fstatfs() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-PRLIMIT", name="prlimit()/prlimit64() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-PERF-EVENT", name="perf_event_open() result used without a <0 test", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-MEMBARRIER", name="membarrier() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-PKEY", name="pkey_alloc() result used without a <0 test", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-SYNCFS", name="syncfs() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-PROCESS-VM", name="process_vm_readv()/process_vm_writev() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-CLONE3", name="clone3() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-FUTEX", name="futex() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-KEYCTL", name="keyctl() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-KCMP", name="kcmp() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-FSOPEN", name="fsopen() result used without a <0 test", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-MQ-OPEN", name="mq_open() result used without a (mqd_t)-1 / <0 test", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-SHMGET", name="shmget() return discarded or used without a <0 test", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-REBOOT", name="reboot() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-ADJTIMEX", name="adjtimex() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-SETHOSTNAME", name="sethostname() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-SWAPON", name="swapon()/swapoff() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-ACCT", name="acct() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-IOPERM", name="ioperm()/iopl() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-MINCORE", name="mincore() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-RSEQ", name="rseq() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-TIMER-CREATE", name="timer_create() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-SEMGET", name="semget() return discarded or used without a <0 test", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-MSGGET", name="msgget() return discarded or used without a <0 test", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-KLOGCTL", name="klogctl() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-MOUNT-SETATTR", name="mount_setattr() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-GETCPU", name="getcpu() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-PROCESS-MRELEASE", name="process_mrelease() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-MEMFD-SECRET", name="memfd_secret() result used without a <0 test", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-IOPRIO", name="ioprio_set()/ioprio_get() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-INIT-MODULE", name="init_module()/finit_module()/delete_module() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-KEXEC", name="kexec_load()/kexec_file_load() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-QUOTACTL-FD", name="quotactl_fd() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-PKEY-FREE", name="pkey_free()/pkey_mprotect() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-TGKILL", name="tgkill() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-ADD-KEY", name="add_key() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-SEMCTL", name="semctl() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-MSGCTL", name="msgctl() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-IO-SETUP", name="io_setup()/io_destroy()/io_cancel()/io_pgetevents() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-REQUEST-KEY", name="request_key() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-TKILL", name="tkill() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-TIMER-DELETE", name="timer_delete()/timer_gettime()/timer_getoverrun() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-MQ-UNLINK", name="mq_unlink()/mq_timedsend()/mq_timedreceive()/mq_notify()/mq_getsetattr() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-SHMAT", name="shmat()/shmdt() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-SEMOP", name="semop()/semtimedop() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-MSGSND", name="msgsnd()/msgrcv() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-SYNC-FILE-RANGE", name="sync_file_range() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-MSYNC", name="msync()/mremap() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-SOCKETPAIR", name="socketpair() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-SYSINFO", name="sysinfo() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-CLOCK-SETTIME", name="clock_settime()/clock_adjtime()/clock_nanosleep() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-SETTIMEOFDAY", name="settimeofday() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-GETTID", name="gettid() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-SCHED-SETSCHEDULER", name="sched_setscheduler()/sched_getscheduler()/sched_setparam()/sched_getparam() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-SETITIMER", name="setitimer()/getitimer() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-NICE", name="nice() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-ARCH-PRCTL", name="arch_prctl() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-GETDENTS", name="getdents()/getdents64() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-UTIMENSAT", name="utimensat()/futimens()/utimes() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-LINKAT", name="linkat() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-MBIND", name="mbind()/set_mempolicy()/get_mempolicy() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-FUTEX-WAITV", name="futex_waitv() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-SYSLOG", name="syslog() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-SETPGID", name="setpgid()/setsid()/getsid() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-SETREUID", name="setreuid()/setregid()/setresuid()/setresgid() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-GETGROUPS", name="getgroups() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-EPOLL-CREATE", name="epoll_create()/epoll_create1() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-TIMERFD-SETTIME", name="timerfd_settime()/timerfd_gettime() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-REMAP-FILE-PAGES", name="remap_file_pages() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-MOVE-PAGES", name="migrate_pages()/move_pages() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-CACHESTAT", name="cachestat() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-MAP-SHADOW-STACK", name="map_shadow_stack() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-SCHED-YIELD", name="sched_yield() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-SETFSUID", name="setfsuid()/setfsgid() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-WAIT4", name="wait4()/wait3() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-PREADV", name="preadv()/pwritev()/preadv2()/pwritev2() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-SENDMSG", name="sendmsg()/recvmsg() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-GETSOCKNAME", name="getsockname()/getpeername() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-EPOLL-PWAIT", name="epoll_pwait()/epoll_pwait2() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-INOTIFY-RM-WATCH", name="inotify_rm_watch() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-EVENTFD-READ", name="eventfd_read()/eventfd_write() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-SCHED-SETATTR", name="sched_setattr()/sched_getattr() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-RENAMEAT2", name="renameat2() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-EXECVEAT", name="execveat() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-MLOCK2", name="mlock2() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-FACCESSAT2", name="faccessat2() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-POSIX-FADVISE", name="posix_fadvise()/posix_fadvise64() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-READAHEAD", name="readahead() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-SIGACTION", name="sigaction() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-SIGPROCMASK", name="sigprocmask()/sigsuspend() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-SEM-OPEN", name="sem_open()/sem_close()/sem_unlink() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-RWLOCK", name="pthread_rwlock_rdlock()/wrlock()/unlock() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-PTHREAD-COND", name="pthread_cond_wait()/timedwait()/signal() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-SIGALTSTACK", name="sigaltstack() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-RENAMEAT", name="renameat() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-FACCESSAT", name="faccessat() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-FCHMODAT", name="fchmodat() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-PTHREAD-BARRIER", name="pthread_barrier_wait()/init()/destroy() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-SYMLINKAT", name="symlinkat() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-UNLINKAT", name="unlinkat() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-MKDIRAT", name="mkdirat() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-MKNODAT", name="mknodat() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-READLINKAT", name="readlinkat() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-FSTATAT", name="fstatat() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-PTHREAD-SPIN", name="pthread_spin_lock()/unlock()/trylock()/init()/destroy() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-PTHREAD-KEY", name="pthread_key_create()/key_delete()/setspecific()/getspecific() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-PTHREAD-CANCEL", name="pthread_cancel() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-PTHREAD-KILL", name="pthread_kill() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-PTHREAD-SIGMASK", name="pthread_sigmask() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-PTHREAD-ATFORK", name="pthread_atfork() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-PLEDGE", name="pledge() return discarded", cwe=[252, 250, 273],
         seen={"lints": FINDS}),
    dict(id="API-UNVEIL", name="unveil() return discarded", cwe=[252, 250, 273],
         seen={"lints": FINDS}),
    dict(id="API-SYSCTL", name="sysctl()/sysctlbyname() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-KQUEUE", name="kqueue() result used without a <0 test or discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-KEVENT", name="kevent() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-PAUSE", name="pause() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-PPOLL", name="ppoll() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-SIGWAIT", name="sigwait()/sigwaitinfo()/sigtimedwait()/sigpending() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-SIGQUEUE", name="sigqueue() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-UCONTEXT", name="getcontext()/setcontext()/swapcontext()/makecontext() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-SEM-TIMEDWAIT", name="sem_timedwait() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-PTHREAD-ATTR", name="pthread_attr_init()/destroy()/setstack*/setdetachstate() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-CAP-ENTER", name="cap_enter() return discarded", cwe=[252, 250, 273],
         seen={"lints": FINDS}),
    dict(id="API-CAP-RIGHTS", name="cap_rights_limit()/cap_rights_get() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-PDFORK", name="pdfork() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-PROCCTL", name="procctl() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-CLOSEFROM", name="closefrom() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-ISSETUGID", name="issetugid() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-ARC4RANDOM", name="arc4random()/arc4random_buf()/arc4random_uniform() return discarded", cwe=[252, 330],
         seen={"lints": FINDS}),
    dict(id="API-CHFLAGS", name="chflags()/fchflags()/lchflags() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-GETFSSTAT", name="getfsstat() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-PTHREAD-YIELD", name="pthread_yield() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-SEM-TRYWAIT", name="sem_trywait()/sem_getvalue() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-ADJTIME", name="adjtime()/ntp_adjtime() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-REVOKE", name="revoke() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-KTRACE", name="ktrace() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-RFORK", name="rfork() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-JAIL", name="jail()/jail_attach()/jail_get()/jail_set()/jail_remove() return discarded", cwe=[252, 250],
         seen={"lints": FINDS}),
    dict(id="API-SETLOGIN", name="setlogin() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-GETRESUID", name="getresuid()/getresgid() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-GETPEEREID", name="getpeereid() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-STRTONUM", name="strtonum() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-REALLOCARRAY", name="reallocarray() return discarded or used without a NULL check", cwe=[252, 190, 680],
         seen={"lints": FINDS}),
    dict(id="API-TIMINGSAFE", name="timingsafe_bcmp()/timingsafe_memcmp() return discarded", cwe=[252, 208],
         seen={"lints": FINDS}),
    dict(id="API-GETPROGNAME", name="getprogname()/setprogname() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-DAEMON", name="daemon()/setproctitle() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-CAP-FCNTLS", name="cap_fcntls_limit()/cap_ioctls_limit() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-PDGETPID", name="pdgetpid()/pdwait4() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-KLDLOAD", name="kldload()/kldunload()/kldfind()/kldsym()/kldstat() return discarded", cwe=[252, 114],
         seen={"lints": FINDS}),
    dict(id="API-EXTATTR", name="extattr_set_file()/extattr_get_file()/extattr_delete_file() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-MAC", name="mac_set_proc()/mac_get_proc()/mac_set_fd() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-AUDIT", name="auditon()/getaudit()/setaudit()/auditctl() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-KVM", name="kvm_open()/kvm_openfiles()/kvm_getprocs()/kvm_close() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-REALLOCF", name="reallocf() return discarded or used without a NULL check", cwe=[252, 401, 680],
         seen={"lints": FINDS}),
    dict(id="API-UUIDGEN", name="uuidgen() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-SETFIB", name="setfib() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-NTP-GETTIME", name="ntp_gettime() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-CRYPT-NEWHASH", name="crypt_newhash()/crypt_checkpass() return discarded", cwe=[252, 916],
         seen={"lints": FINDS}),
    dict(id="API-WAIT6", name="wait6() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-CPUSET", name="cpuset_setaffinity()/cpuset_getaffinity() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-RTPRIO", name="rtprio()/rtprio_thread() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-KENV", name="kenv() return discarded", cwe=[252, 526],
         seen={"lints": FINDS}),
    dict(id="API-GETFH", name="getfh()/fhopen()/fhstat()/fhstatfs() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-GETMNTINFO", name="getmntinfo() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-NMOUNT", name="nmount() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-STRMODE", name="strmode() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-GETOSRELDATE", name="getosreldate() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-CAP-SANDBOXED", name="cap_sandboxed() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-GETGROUPLIST", name="getgrouplist() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-EACCESS", name="eaccess() return discarded", cwe=[252, 284],
         seen={"lints": FINDS}),
    dict(id="API-LOGIN-GETCLASS", name="login_getclass()/setusercontext() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-FFLAGS", name="fflagstostr()/strtofflags() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-GETDIRENTRIES", name="getdirentries() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-KINFO", name="kinfo_getproc()/kinfo_getfile() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-UMTX", name="_umtx_op() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-THR", name="thr_new()/thr_kill()/thr_kill2() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-MODFIND", name="modfind()/modstat()/modnext() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-LPATHCONF", name="lpathconf() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-LOGINCLASS", name="getloginclass()/setloginclass() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-GETFSENT", name="getfsent()/setfsent()/endfsent() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-MINHERIT", name="minherit() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-CAP-GETMODE", name="cap_getmode() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-NFSSVC", name="nfssvc() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-SYSARCH", name="sysarch() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-GETPAGESIZES", name="getpagesizes() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-SBRK", name="sbrk()/brk() return discarded", cwe=[252, 770],
         seen={"lints": FINDS}),
    dict(id="API-KSEM", name="ksem_open()/ksem_close()/ksem_unlink() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-CAP-GETRIGHTS", name="cap_getrights() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-DEVNAME", name="devname()/devname_r() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-GETBOOTFILE", name="getbootfile() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-KLDFIRSTMOD", name="kldfirstmod()/kldnextmod() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-FHLINK", name="fhlink()/fhlinkat()/fhreadlink() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="API-VALLOC", name="valloc() return discarded or used without a NULL check", cwe=[252, 590],
         seen={"lints": FINDS}),
    dict(id="API-GETDOMAINNAME", name="getdomainname() return discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="STR-STRNCPY-NUL", name="strncpy into local array without an explicit NUL store", cwe=[170],
         seen={"lints": FINDS}),
    dict(id="MEM-VLA-SIZE", name="variable-length local array", cwe=[758],
         seen={"lints": FINDS}),
    dict(id="MEM-ALLOCA", name="alloca size is not a constant", cwe=[770, 1325],
         seen={"lints": FINDS}),
    dict(id="MEM-FLEX-ARRAY", name="flexible-array struct allocated at header size only", cwe=[131, 119],
         seen={"lints": FINDS}),
    dict(id="MEM-LEAK", name="heap allocation freed on some returns only", cwe=[401],
         seen={"lints": FINDS}),
    dict(id="STR-NULL-ARG", name="string API called on unchecked pointer parameter", cwe=[476],
         seen={"lints": FINDS}),
    dict(id="CXX-USE-AFTER-MOVE", name="value used after std::move", cwe=[672],
         seen={"lints": FINDS}),
    dict(id="CXX-DANGLING-REF", name="view or span borrows local storage", cwe=[416],
         seen={"lints": FINDS}),
    dict(id="CXX-ITERATOR-INVALID", name="iterator used after container mutation", cwe=[119],
         seen={"lints": FINDS}),
    dict(id="CXX-SELF-ASSIGN", name="assignment without self-test", cwe=[762],
         seen={"lints": FINDS}),
    dict(id="CXX-DELETE-THIS", name="delete this while the member function still runs", cwe=[416],
         seen={"lints": FINDS}),
    dict(id="CXX-CATCH-BY-VALUE", name="exception caught by value (slicing)", cwe=[704],
         seen={"lints": FINDS}),
    dict(id="CXX-THROW-NOEXCEPT", name="throw in noexcept or throw() function", cwe=[248],
         seen={"lints": FINDS}),
    dict(id="CXX-MISSING-VIRTUAL-DTOR", name="delete base pointer to class without virtual destructor", cwe=[762],
         seen={"lints": FINDS}),
    dict(id="CXX-LAMBDA-DANGLE", name="returned lambda captures local by reference", cwe=[416, 562],
         seen={"lints": FINDS}),
    dict(id="CXX-UNIQUE-RESET", name="raw pointer from unique_ptr::get used after reset", cwe=[416],
         seen={"lints": FINDS}),
    dict(id="CXX-CONST-CAST", name="const_cast write through formerly const object", cwe=[704, 758],
         seen={"lints": FINDS}),
    dict(id="CXX-DYNAMIC-CAST-NULL", name="dynamic_cast result used without null test", cwe=[476],
         seen={"lints": FINDS}),
    dict(id="CXX-REINTERPRET", name="reinterpret_cast type-puns object pointers", cwe=[704],
         seen={"lints": FINDS}),
    dict(id="CXX-THROW-COPY", name="throw caught exception object (slicing)", cwe=[703],
         seen={"lints": FINDS}),
    dict(id="CXX-BIT-CAST", name="bit_cast between object pointer and integer or unrelated object types", cwe=[704],
         seen={"lints": FINDS}),
    dict(id="CXX-PLACEMENT-NEW", name="placement new into a typed object pointer", cwe=[704, 762],
         seen={"lints": FINDS}),
    dict(id="CXX-STD-THREAD", name="std::thread not joined or detached", cwe=[833],
         seen={"lints": FINDS}),
    dict(id="CXX-OPTIONAL-NULL", name="dereference of std::optional without has_value", cwe=[476],
         seen={"lints": FINDS}),
    dict(id="CXX-VARIANT-GET", name="std::get without holds_alternative", cwe=[704],
         seen={"lints": FINDS}),
    dict(id="CXX-SPAN-DANGLE", name="std::span constructed from a local then returned", cwe=[416],
         seen={"lints": FINDS}),
    dict(id="CXX-VECTOR-INDEX", name="vector/string subscript without a size guard", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-CATCH-ALL", name="empty catch (...) swallows exceptions", cwe=[703],
         seen={"lints": FINDS}),
    dict(id="CXX-THROW-NEW", name="throw new allocates the exception with new", cwe=[248],
         seen={"lints": FINDS}),
    dict(id="CXX-UNINIT-MEMBER", name="constructor leaves a scalar member uninitialised", cwe=[457],
         seen={"lints": FINDS}),
    dict(id="CXX-COPY-ASSIGN-PTR", name="operator= shallow-copies a raw pointer member", cwe=[762],
         seen={"lints": FINDS}),
    dict(id="CXX-VOLATILE-CAST", name="C-style cast away from volatile then write", cwe=[758],
         seen={"lints": FINDS}),
    dict(id="CXX-SHARED-PTR-GET", name="raw pointer from shared_ptr::get used after reset", cwe=[416],
         seen={"lints": FINDS}),
    dict(id="CXX-AUTO-PTR", name="use of deprecated std::auto_ptr", cwe=[676],
         seen={"lints": FINDS}),
    dict(id="CXX-STRING-DATA", name="pointer from string c_str/data used after mutation", cwe=[416],
         seen={"lints": FINDS}),
    dict(id="CXX-ENABLE-SHARED", name="shared_from_this without enable_shared_from_this", cwe=[664],
         seen={"lints": FINDS}),
    dict(id="CXX-FORWARDING-REF", name="T&& pushed into a container without std::forward", cwe=[704],
         seen={"lints": FINDS}),
    dict(id="CXX-EXPLICIT-CTOR", name="operator bool conversion without explicit", cwe=[704],
         seen={"lints": FINDS}),
    dict(id="CXX-MOVE-CONST", name="std::move of a const object", cwe=[704],
         seen={"lints": FINDS}),
    dict(id="CXX-BIND-TMP", name="reference bound to a temporary then returned", cwe=[562],
         seen={"lints": FINDS}),
    dict(id="CXX-EXPECTED-NULL", name="std::expected value accessed without has_value", cwe=[476],
         seen={"lints": FINDS}),
    dict(id="CXX-STD-FORMAT", name="std::format/print with a non-literal format string", cwe=[134],
         seen={"lints": FINDS}),
    dict(id="CXX-THIS-CAPTURE", name="returned lambda captures this by [=] or [this]", cwe=[416, 562],
         seen={"lints": FINDS}),
    dict(id="CXX-SPACESHIP-DEFAULT", name="defaulted operator<=> with a pointer member", cwe=[704],
         seen={"lints": FINDS}),
    dict(id="CXX-STD-ASYNC", name="std::async result discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="CXX-FUTURE-GET", name="std::future::get without a prior assignment", cwe=[394],
         seen={"lints": FINDS}),
    dict(id="CXX-STD-FUNCTION-NULL", name="std::function invoked without a truth test", cwe=[476],
         seen={"lints": FINDS}),
    dict(id="CXX-NODISCARD", name="[[nodiscard]] result discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="CXX-STD-JTHREAD", name="std::jthread constructed without request_stop", cwe=[833],
         seen={"lints": FINDS}),
    dict(id="CXX-MDSPAN-DANGLE", name="std::mdspan constructed from a local then returned", cwe=[416],
         seen={"lints": FINDS}),
    dict(id="CXX-ATOMIC-REF", name="std::atomic_ref constructed from a local then returned", cwe=[416],
         seen={"lints": FINDS}),
    dict(id="CXX-CONDITION-WAIT", name="condition_variable wait without a predicate", cwe=[662],
         seen={"lints": FINDS}),
    dict(id="CXX-STD-BIND", name="use of std::bind; prefer a lambda", cwe=[676],
         seen={"lints": FINDS}),
    dict(id="CXX-ASSUME", name="[[assume(false)]] / [[assume(0)]] in a function that still returns", cwe=[758],
         seen={"lints": FINDS}),
    dict(id="CXX-GENERATOR", name="std::generator yields a pointer or reference to a local", cwe=[416],
         seen={"lints": FINDS}),
    dict(id="CXX-SHARED-MUTEX", name="std::shared_mutex lock() without unlock or lock_guard", cwe=[667],
         seen={"lints": FINDS}),
    dict(id="CXX-ANY-CAST", name="std::any_cast by value without type check or pointer form", cwe=[704],
         seen={"lints": FINDS}),
    dict(id="CXX-FILESYSTEM", name="std::filesystem::remove then use of the same path", cwe=[367],
         seen={"lints": FINDS}),
    dict(id="CXX-REGEX", name="std::regex constructed from a non-literal pattern", cwe=[185],
         seen={"lints": FINDS}),
    dict(id="CXX-LATCH", name="std::latch wait without count_down in the same function", cwe=[667],
         seen={"lints": FINDS}),
    dict(id="CXX-FROM-CHARS", name="std::from_chars result used without checking ec", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="CXX-INIT-LIST-DANGLE", name="pointer from a temporary initializer_list used after the full-expression", cwe=[562],
         seen={"lints": FINDS}),
    dict(id="CXX-STOP-TOKEN", name="infinite loop with stop_token and no stop_requested", cwe=[833],
         seen={"lints": FINDS}),
    dict(id="CXX-FLAT-MAP", name="flat_map at() without contains/count/find", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-SEMAPHORE", name="counting_semaphore acquire without release in the same function", cwe=[667],
         seen={"lints": FINDS}),
    dict(id="CXX-STACKTRACE", name="stacktrace::current() [0]/at(0) without empty/size check", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-UNIQUE-RELEASE", name="unique_ptr get used after release", cwe=[416],
         seen={"lints": FINDS}),
    dict(id="CXX-PACK-PRAGMA", name="address of a non-char member of a #pragma pack(1) struct", cwe=[188],
         seen={"lints": FINDS}),
    dict(id="CXX-FUNCTION-REF", name="function_ref bound to a temporary lambda or call", cwe=[416, 562],
         seen={"lints": FINDS}),
    dict(id="CXX-MOVE-ONLY-FUNCTION", name="move_only_function invoked without a truth test", cwe=[476],
         seen={"lints": FINDS}),
    dict(id="CXX-RANGES-DANGLE", name="ranges view pipeline over a temporary range", cwe=[416],
         seen={"lints": FINDS}),
    dict(id="CXX-CHRONO-SEED", name="PRNG seeded from chrono clock::now()", cwe=[330],
         seen={"lints": FINDS}),
    dict(id="CXX-INPLACE-VECTOR", name="inplace_vector push_back without size/capacity guard", cwe=[787],
         seen={"lints": FINDS}),
    dict(id="CXX-FLAT-SET", name="flat_set find dereference without end() check", cwe=[476],
         seen={"lints": FINDS}),
    dict(id="CXX-COPYABLE-FUNCTION", name="copyable_function invoked without a truth test", cwe=[476],
         seen={"lints": FINDS}),
    dict(id="CXX-HIVE", name="hive iterator used after insert/emplace/erase", cwe=[119],
         seen={"lints": FINDS}),
    dict(id="CXX-BITSET-INDEX", name="bitset test/subscript without a size guard", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-SSTREAM-VIEW", name="string_view or c_str of stringstream::str() temporary", cwe=[416],
         seen={"lints": FINDS}),
    dict(id="CXX-OPTIONAL-VALUE", name="optional.value() without has_value", cwe=[476],
         seen={"lints": FINDS}),
    dict(id="CXX-INDIRECT", name="dereference of default-constructed empty std::indirect", cwe=[476],
         seen={"lints": FINDS}),
    dict(id="CXX-TO-CHARS", name="std::to_chars result used without checking ec/ptr", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="CXX-HAZARD-POINTER", name="hazard_pointer constructed but atomic load used without protect", cwe=[416],
         seen={"lints": FINDS}),
    dict(id="CXX-TEXT-ENCODING", name="std::text_encoding constructed from a non-literal name", cwe=[176],
         seen={"lints": FINDS}),
    dict(id="CXX-EXPECTED-ERROR", name="std::expected error() without a prior !e / !has_value check", cwe=[390],
         seen={"lints": FINDS}),
    dict(id="CXX-VARIANT-VALUELSS", name="std::get after emplace without valueless_by_exception check", cwe=[704],
         seen={"lints": FINDS}),
    dict(id="CXX-SIMD-INDEX", name="std::simd subscript without a size guard", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-RCU", name="rcu_obj update or retire without rcu_synchronize", cwe=[416],
         seen={"lints": FINDS}),
    dict(id="CXX-LINALG", name="linalg matrix index without an extents guard", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-SYNC-WAIT", name="std::execution::sync_wait result discarded", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="CXX-EMBED", name="#embed used as a pointer without a size, or non-literal embed path", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-CONTRACTS", name="contract_assert(false)/pre(false) in a function that still returns", cwe=[758],
         seen={"lints": FINDS}),
    dict(id="CXX-REFLECTION", name="std::meta define_aggregate/define_class without a named namespace", cwe=[284],
         seen={"lints": FINDS}),
    dict(id="CXX-OUT-PTR", name="unique_ptr/shared_ptr used after out_ptr without a null check", cwe=[476],
         seen={"lints": FINDS}),
    dict(id="CXX-FLAT-MULTIMAP", name="flat_multimap find dereference without end() check", cwe=[476],
         seen={"lints": FINDS}),
    dict(id="CXX-SPANSTREAM", name="spanstream span() data or string_view outlives the stream", cwe=[416],
         seen={"lints": FINDS}),
    dict(id="CXX-BARRIER", name="std::barrier arrive without wait in the same function", cwe=[667],
         seen={"lints": FINDS}),
    dict(id="CXX-TASK", name="std::task started without sync_wait or co_await", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="CXX-GENERATOR-DISCARD", name="std::generator constructed and not iterated", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="CXX-OSYNCSTREAM", name="osyncstream destroyed without emit()", cwe=[662],
         seen={"lints": FINDS}),
    dict(id="CXX-PACKAGED-TASK", name="packaged_task invoked without a truth test", cwe=[476],
         seen={"lints": FINDS}),
    dict(id="CXX-FLAT-MULTISET", name="flat_multiset find dereference without end() check", cwe=[476],
         seen={"lints": FINDS}),
    dict(id="CXX-SYNCBUF", name="syncbuf destroyed without emit()", cwe=[662],
         seen={"lints": FINDS}),
    dict(id="CXX-COUNTED-ITERATOR", name="counted_iterator constructed without a count vs remaining-size guard", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-PROMISE", name="promise get_future used without set_value/set_exception", cwe=[394],
         seen={"lints": FINDS}),
    dict(id="CXX-WEAK-PTR", name="weak_ptr.lock() used without expired() or a truth test", cwe=[416],
         seen={"lints": FINDS}),
    dict(id="CXX-EXCEPTION-PTR", name="exception_ptr rethrown without a nullptr test", cwe=[476],
         seen={"lints": FINDS}),
    dict(id="CXX-CORO-HANDLE", name="coroutine_handle.resume() without done()", cwe=[762],
         seen={"lints": FINDS}),
    dict(id="CXX-VALARRAY", name="valarray operator[] without a size() guard", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-TO-UNDERLYING", name="to_underlying used without an enum-range guard", cwe=[704],
         seen={"lints": FINDS}),
    dict(id="CXX-UNEXPECTED", name="std::unexpected< constructed and discarded (not used as expected error path)", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="CXX-TUPLE-GET", name="std::get on tuple without a tuple_size/index-in-range guard", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-DEQUE-INDEX", name="deque operator[] without size()", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-FORWARD-LIST", name="forward_list.front() without empty()", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-LIST-FRONT", name="std::list.front()/.back() without empty()", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-MAP-AT", name="std::map .at( without count()/find()/contains()", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-UNORDERED-AT", name="unordered_map .at( without count()/find()/contains()", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-SET-FIND", name="std::set find dereference without end()", cwe=[476],
         seen={"lints": FINDS}),
    dict(id="CXX-QUEUE-FRONT", name="std::queue .front()/.pop() without empty()", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-STACK-TOP", name="std::stack .top()/.pop() without empty()", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-PRIORITY-QUEUE", name="std::priority_queue .top()/.pop() without empty()", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-ARRAY-INDEX", name="std::array operator[] without size()/N guard", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-UNORDERED-SET", name="unordered_set find dereference without end()", cwe=[476],
         seen={"lints": FINDS}),
    dict(id="CXX-WSTRING-VIEW", name="wstring_view / wstring borrows local storage", cwe=[416],
         seen={"lints": FINDS}),
    dict(id="CXX-MULTIMAP-FIND", name="std::multimap find dereference without end()", cwe=[476],
         seen={"lints": FINDS}),
    dict(id="CXX-MULTISET-FIND", name="std::multiset find dereference without end()", cwe=[476],
         seen={"lints": FINDS}),
    dict(id="CXX-BINARY-SEMAPHORE", name="binary_semaphore(0) acquire without try_acquire or release", cwe=[667],
         seen={"lints": FINDS}),
    dict(id="CXX-ERROR-CODE", name="std::error_code used without if(ec) or .value() check", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="CXX-BYTESWAP", name="byteswap result used as array index without a range check", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-PMR", name="std::pmr container operator[] without size() guard", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-U8STRING-VIEW", name="u8string_view / u8string borrows local storage", cwe=[416],
         seen={"lints": FINDS}),
    dict(id="CXX-UNORDERED-MULTIMAP", name="unordered_multimap find dereference without end()", cwe=[476],
         seen={"lints": FINDS}),
    dict(id="CXX-UNORDERED-MULTISET", name="unordered_multiset find dereference without end()", cwe=[476],
         seen={"lints": FINDS}),
    dict(id="CXX-SHARED-LOCK", name="std::shared_lock used without owns_lock() check", cwe=[667],
         seen={"lints": FINDS}),
    dict(id="CXX-ATOMIC-FLAG", name="atomic_flag.test_and_set without a prior clear()", cwe=[667],
         seen={"lints": FINDS}),
    dict(id="CXX-CONDVAR-ANY", name="condition_variable_any.wait without a lock / predicate", cwe=[662],
         seen={"lints": FINDS}),
    dict(id="CXX-RECURSIVE-MUTEX", name="recursive_mutex.lock() without unlock or lock_guard", cwe=[667],
         seen={"lints": FINDS}),
    dict(id="CXX-TIMED-MUTEX", name="timed_mutex try_lock/lock result discarded or lock without unlock", cwe=[667],
         seen={"lints": FINDS}),
    dict(id="CXX-FSTREAM", name="ifstream/ofstream used without is_open() or a truth test", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="CXX-THIS-THREAD", name="this_thread::sleep_for as the only sync around a shared store", cwe=[362, 667],
         seen={"lints": FINDS}),
    dict(id="CXX-CALL-ONCE", name="std::call_once without an once_flag object in scope", cwe=[662],
         seen={"lints": FINDS}),
    dict(id="CXX-SHARED-TIMED-MUTEX", name="shared_timed_mutex.lock/lock_shared without unlock", cwe=[667],
         seen={"lints": FINDS}),
    dict(id="CXX-RECURSIVE-TIMED-MUTEX", name="recursive_timed_mutex.lock() without unlock", cwe=[667],
         seen={"lints": FINDS}),
    dict(id="CXX-SYSTEM-ERROR", name="std::system_error used without a .code() check", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="CXX-CHRONO-TZDB", name="chrono current_zone/tzdb used without a null/locate check", cwe=[252, 476],
         seen={"lints": FINDS}),
    dict(id="CXX-RANGES-ZIP", name="views::zip / zip_view indexed or iterated without a size guard", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-FORMAT-TO", name="format_to into a raw char buffer without size / format_to_n", cwe=[120],
         seen={"lints": FINDS}),
    dict(id="CXX-ERROR-CATEGORY", name="error_category used without generic/system compare or .message()", cwe=[252],
         seen={"lints": FINDS}),
    dict(id="CXX-NESTED-EXCEPTION", name="throw_with_nested / nested_exception without a try/catch", cwe=[705],
         seen={"lints": FINDS}),
    dict(id="CXX-ATOMIC-FENCE", name="atomic_thread_fence without memory_order or as only sync around a store", cwe=[362],
         seen={"lints": FINDS}),
    dict(id="CXX-NOTIFY-THREAD-EXIT", name="notify_all_at_thread_exit without a waiting condition_variable", cwe=[662],
         seen={"lints": FINDS}),
    dict(id="CXX-WSTRING-CONVERT", name="wstring_convert without .converted() or dangling local converter", cwe=[416, 252],
         seen={"lints": FINDS}),
    dict(id="CXX-INVOKE", name="std::invoke on a nullable callable without a truth test", cwe=[476],
         seen={"lints": FINDS}),
    dict(id="CXX-APPLY", name="std::apply on a tuple without a size/tuple_size guard, or apply of a nullable callable", cwe=[476],
         seen={"lints": FINDS}),
    dict(id="CXX-REFERENCE-WRAPPER", name="std::ref/cref/reference_wrapper wrapping a local that is returned or escaped", cwe=[416],
         seen={"lints": FINDS}),
    dict(id="CXX-ENDIAN", name="std::endian used as an array index or unchecked integer without a range check", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-BIT-CEIL", name="bit_ceil/bit_floor/has_single_bit/popcount used as an index without a range check, or bit_ceil(0)", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-UNCAUGHT-EXCEPTIONS", name="std::uncaught_exceptions() used as a destructor-safety check without comparing to a saved count", cwe=[705],
         seen={"lints": FINDS}),
    dict(id="CXX-RANGES-JOIN", name="views::join / join_view indexed or iterated without a size guard", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-QUICK-EXIT", name="std::quick_exit / at_quick_exit without a prior at_quick_exit handler, or quick_exit from a destructor", cwe=[670],
         seen={"lints": FINDS}),
    dict(id="CXX-TO-ARRAY", name="std::to_array of a local C array then the source is mutated/destroyed while the std::array is used, or to_array result indexed without size", cwe=[125, 416],
         seen={"lints": FINDS}),
    dict(id="CXX-ZONED-TIME", name="std::chrono::zoned_time constructed without a zone / locate_zone null check", cwe=[476],
         seen={"lints": FINDS}),
    dict(id="CXX-KILL-DEPENDENCY", name="std::kill_dependency used as the only sync around a shared store, or result used as an index without a range check", cwe=[362, 125],
         seen={"lints": FINDS}),
    dict(id="CXX-ROTL", name="std::rotl/std::rotr result used as an array index without a range check", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-CURRENT-EXCEPTION", name="std::current_exception() used without a nullptr test before rethrow_exception", cwe=[476],
         seen={"lints": FINDS}),
    dict(id="CXX-BIT-WIDTH", name="std::bit_width result used as an array index without a range check", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-LERP", name="std::lerp result used as an array index without a range check, or lerp with no finite bounds", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-MIDPOINT", name="std::midpoint result used as an array index without a range check", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-CMP-LESS", name="std::cmp_less/in_range result used as an array index, or in_range ignored before a subscript", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-COUNTL-ZERO", name="std::countl_zero/countr_zero/countl_one/countr_one result used as an array index without a range check", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-UNREACHABLE", name="std::unreachable() used as a recoverable path or in a function that also returns", cwe=[670],
         seen={"lints": FINDS}),
    dict(id="CXX-GCD", name="std::gcd result used as an array index without a range check", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-LCM", name="std::lcm result used as an array index without a range check", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-CLAMP", name="std::clamp result used as an array index without a range check", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-EXCHANGE", name="std::exchange used then the old value is used after the exchange, or exchange result used as an unguarded index", cwe=[672, 125],
         seen={"lints": FINDS}),
    dict(id="CXX-TO-ADDRESS", name="std::to_address on a local unique_ptr/raw pointer then the source is reset/destroyed while the raw pointer is used, or to_address result indexed without a bound", cwe=[416, 125],
         seen={"lints": FINDS}),
    dict(id="CXX-IS-CONSTANT-EVALUATED", name="std::is_constant_evaluated() used to pick an unchecked runtime index path", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-ADDRESSOF", name="std::addressof result used as an array index or stored then the object dies", cwe=[125, 416],
         seen={"lints": FINDS}),
    dict(id="CXX-ASSUME-ALIGNED", name="std::assume_aligned result indexed without a bound", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-AS-CONST", name="std::as_const used to then const_cast away constness and write, or as_const view of a local then the local dies", cwe=[119, 416],
         seen={"lints": FINDS}),
    dict(id="CXX-EXCLUSIVE-SCAN", name="std::exclusive_scan output buffer indexed/used without a size guard, or dest overlaps source", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-MAKE-EXCEPTION-PTR", name="std::make_exception_ptr / the resulting exception_ptr rethrown without a nullptr test", cwe=[476],
         seen={"lints": FINDS}),
    dict(id="CXX-SET-TERMINATE", name="std::set_terminate / get_terminate used without storing the previous handler, or terminate handler itself throws", cwe=[670],
         seen={"lints": FINDS}),
    dict(id="CXX-INCLUSIVE-SCAN", name="std::inclusive_scan output buffer indexed/used without a size guard, or dest overlaps source", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-TRANSFORM-REDUCE", name="std::transform_reduce result used as an array index without a range check", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-REDUCE", name="std::reduce result used as an array index without a range check", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-UNINITIALIZED-COPY", name="std::uninitialized_copy/uninitialized_move into a buffer without constructing/lifetime, or dest indexed OOB", cwe=[125, 824],
         seen={"lints": FINDS}),
    dict(id="CXX-CONSTRUCT-AT", name="std::construct_at/destroy_at on storage then the pointer is used after destroy, or construct_at result indexed OOB", cwe=[416, 125],
         seen={"lints": FINDS}),
    dict(id="CXX-FORWARD-LIKE", name="std::forward_like used then the source is moved-from and used", cwe=[672],
         seen={"lints": FINDS}),
    dict(id="CXX-UNINITIALIZED-FILL", name="std::uninitialized_fill/uninitialized_default_construct dest indexed OOB", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-DESTROY-N", name="std::destroy_n then the range is used, or count is unchecked", cwe=[416],
         seen={"lints": FINDS}),
    dict(id="CXX-ADD-SAT", name="std::add_sat/sub_sat/mul_sat/div_sat/saturate_cast result used as an array index without a range check", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-TRANSFORM-SCAN", name="std::transform_inclusive_scan/transform_exclusive_scan output indexed without a size guard", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-TYPE-IDENTITY", name="std::type_identity used to recast a pointer then indexed OOB", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-NONTYPE", name="std::nontype used as an unguarded index or to bypass a bound", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-LAYOUT-COMPATIBLE", name="std::is_layout_compatible used to recast then indexed OOB", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-PTR-INTERCONVERTIBLE", name="is_pointer_interconvertible_with_class / is_pointer_interconvertible_base_of used to recast then indexed OOB", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-UNINITIALIZED-VALUE", name="std::uninitialized_value_construct dest indexed OOB", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-CONST-ITERATOR", name="std::basic_const_iterator used then written through or indexed OOB", cwe=[125, 664],
         seen={"lints": FINDS}),
    dict(id="CXX-CORRESPONDING-MEMBER", name="std::is_corresponding_member used to recast then indexed OOB", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-RANGES-TO", name="std::ranges::to into a container then indexed without a size guard", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-ENUMERATE", name="std::views::enumerate / enumerate_view indexed without a size guard", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-CARTESIAN-PRODUCT", name="std::views::cartesian_product indexed without a size guard", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-CHUNK", name="std::views::chunk / chunk_by / chunk_view indexed without a size guard", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-SLIDE", name="std::views::slide / slide_view indexed without a size guard", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-ADJACENT", name="std::views::adjacent / adjacent_transform / adjacent_view indexed without a size guard", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-JOIN-WITH", name="std::views::join_with / join_with_view indexed without a size guard", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-ZIP-TRANSFORM", name="std::views::zip_transform / zip_transform_view indexed without a size guard", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-AS-RVALUE", name="std::views::as_rvalue / as_rvalue_view indexed OOB or used after the source dies", cwe=[125, 664],
         seen={"lints": FINDS}),
    dict(id="CXX-FROM-RANGE", name="std::from_range used to build a container then indexed without a size guard", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-SCOPED-ENUM", name="std::is_scoped_enum used to recast then indexed OOB", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-STRIDE", name="std::views::stride / stride_view indexed without a size guard", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-REPEAT", name="std::views::repeat / repeat_view indexed without a size guard", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-TAKE", name="std::views::take / take_view indexed without a size guard", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-DROP", name="std::views::drop / drop_view indexed without a size guard", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-FILTER", name="std::views::filter / filter_view indexed without a size guard", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-TRANSFORM-VIEW", name="std::views::transform / transform_view indexed without a size guard", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-ELEMENTS", name="std::views::elements / elements_view indexed without a size guard", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-IOTA", name="std::views::iota / iota_view indexed without a size guard", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-TAKE-WHILE", name="std::views::take_while / take_while_view indexed without a size guard", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-DROP-WHILE", name="std::views::drop_while / drop_while_view indexed without a size guard", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-KEYS", name="std::views::keys / keys_view indexed without a size guard", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-VALUES", name="std::views::values / values_view indexed without a size guard", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-REVERSE-VIEW", name="std::views::reverse / reverse_view indexed without a size guard", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="CXX-COUNTED", name="std::views::counted / counted_view indexed without a size guard", cwe=[125],
         seen={"lints": FINDS}),
    dict(id="MEM-MISMATCHED-FREE", name="malloc/free vs new/delete mismatch", cwe=[762],
         seen={"lints": FINDS}),
    dict(id="MEM-PTR-ARITH", name="pointer index without bound or null guard", cwe=[125, 787],
         seen={"lints": FINDS}),
    dict(id="FLOAT-UB", name="division by floating zero literal", cwe=[369],
         seen={"lints": FINDS}),
    dict(id="EMPTY-TU", name="translation unit parsed no functions", cwe=[],
         seen={"inventory": FINDS}),
    dict(id="PARSE-GAP", name="code in braces the parser attributed to no function", cwe=[],
         seen={"inventory": FINDS}),
    dict(id="LTL-SAFETY", name="LTL safety violation", cwe=[],
         seen={"ltl": PROVES, "strix": PROVES}),
    dict(id="FUNC-CONTRACT", name="ensures clause fails", cwe=[],
         seen={"bmc": PROVES, "pir": PROVES, "dafny": PROVES, "wp": PROVES, "contracts": PROVES,
               "rapid": FINDS, "muttest": SOME, "llm": READS}),
    dict(id="INTENT", name="comment/code contract mismatch", cwe=[],
         seen={"lints": FINDS, "llm": READS}),
    dict(id="VACUOUS-ASSUMPTION", name="requires/harness assumption no input satisfies (vacuous proof)",
         cwe=[], seen={"review": PROVES}),
    dict(id="PROOF-REGRESSION", name="a stored proof no longer checks after a change", cwe=[],
         seen={"review": FINDS}),
    dict(id="INFOLEAK-PAD", name="struct padding copied without zero-init", cwe=[200],
         seen={"lints": FINDS}),
    dict(id="API-PRECONDITION", name="documented precondition unchecked in body", cwe=[],
         seen={"lints": FINDS, "llm": READS}),
    dict(id="TRUST-UNVALIDATED-INPUT", name="parsed input used without range check", cwe=[20, 1284],
         seen={"lints": FINDS, "taint": SOME}),
    dict(id="CRYPTO-MISUSE", name="rand() used as cryptographic key material", cwe=[330, 338],
         seen={"lints": FINDS}),
    dict(id="CRYPTO-SRAND", name="srand(time()) seeds PRNG from clock", cwe=[330],
         seen={"lints": FINDS}),
    dict(id="TAINT-SINK", name="untrusted input reaches dangerous sink", cwe=[78, 134],
         seen={"taint": FINDS}),
    dict(id="RACE-SHARED", name="unsynchronized write to shared global", cwe=[362, 366],
         seen={"thread": FINDS}),
    dict(id="SYNTAX-ERROR", name="source does not parse", cwe=[],
         seen={"polyglot": FINDS}),
    dict(id="TYPE-ERROR", name="static type error", cwe=[],
         seen={"polyglot": FINDS}),
    dict(id="LANG-LINT", name="language linter diagnostic", cwe=[],
         seen={"polyglot": FINDS}),
    dict(id="VCS-CONFLICT-MARKER", name="unresolved merge conflict marker", cwe=[],
         seen={"polyglot": FINDS}),
    dict(id="SECRET-PRIVATE-KEY", name="private key committed in source", cwe=[321],
         seen={"polyglot": FINDS}),
    dict(id="SECRET-AWS-KEY", name="AWS access key committed in source", cwe=[798],
         seen={"polyglot": FINDS}),
    dict(id="SECRET-GITHUB-TOKEN", name="GitHub token committed in source", cwe=[798],
         seen={"polyglot": FINDS}),
    dict(id="SECRET-SLACK-TOKEN", name="Slack token committed in source", cwe=[798],
         seen={"polyglot": FINDS}),
    dict(id="SECRET-GOOGLE-API-KEY", name="Google API key committed in source", cwe=[798],
         seen={"polyglot": FINDS}),
    dict(id="SECRET-STRIPE-KEY", name="Stripe live key committed in source", cwe=[798],
         seen={"polyglot": FINDS}),
    # PIR memory model and library models (docs/PIR.md; C++ engine pir stage)
    dict(id="PTR-INVALID-DEREF", name="dereference of a pointer that points to no object", cwe=[822, 824],
         seen={"pir": PROVES}),
    dict(id="MEM-MISALIGNED", name="misaligned memory access", cwe=[704],
         seen={"pir": PROVES}),
    dict(id="MEM-WRITE-CONST", name="write to a string literal or const object", cwe=[758],
         seen={"pir": PROVES}),
    dict(id="MEM-STRICT-ALIAS", name="object accessed through an lvalue of an incompatible type (effective type)", cwe=[704, 843],
         seen={"pir": PROVES}),
    dict(id="MEM-INVALID-FREE", name="free of memory that is not a live heap object or not its start", cwe=[590, 761],
         seen={"pir": PROVES}),
    dict(id="PTR-COMPARE", name="comparison or subtraction of pointers into different objects", cwe=[469],
         seen={"pir": PROVES}),
    dict(id="FMT-ARGS", name="printf format does not match its arguments", cwe=[685, 686],
         seen={"pir": PROVES}),
    # PIR floating point, exceptions, setjmp/longjmp (docs/PIR.md; roadmap 2.6)
    dict(id="FLOAT-CAST-OVF", name="floating-point value converted to an integer type that cannot represent it", cwe=[681],
         seen={"pir": PROVES}),
    dict(id="FLOAT-DIV-ZERO", name="floating-point division by zero (pir --fp-checks)", cwe=[369],
         seen={"pir": PROVES}),
    dict(id="FLOAT-INVALID", name="floating-point invalid operation produces NaN (pir --fp-checks)", cwe=[682],
         seen={"pir": PROVES}),
    dict(id="FLOAT-OVERFLOW", name="floating-point overflow to infinity (pir --fp-checks)", cwe=[682],
         seen={"pir": PROVES}),
    dict(id="CXX-UNCAUGHT", name="exception escapes main: std::terminate", cwe=[248],
         seen={"pir": PROVES}),
    dict(id="CXX-TERMINATE", name="std::terminate reached (rethrow without a handled exception, explicit call)", cwe=[248],
         seen={"pir": PROVES}),
    dict(id="CXX-PURE-VIRTUAL", name="pure virtual function called", cwe=[758],
         seen={"pir": PROVES}),
    dict(id="CTRL-LONGJMP-INVALID", name="longjmp to a jmp_buf whose setjmp caller has returned", cwe=[758],
         seen={"pir": PROVES}),
]


def coverage_row(available: set[str]) -> list[dict]:
    """Capability map: which instruments *could* see a class if they ran.

    Silence of a FINDS instrument is not COVERED. Prefer coverage_from_report.
    """
    rows = []
    for c in CLASSES:
        best = None
        rank = {PROVES: 3, FINDS: 2, SOME: 1, READS: 1}
        for inst, how in c["seen"].items():
            if inst not in available:
                continue
            if best is None or rank[how] > rank[best]:
                best = how
        if best in (PROVES, FINDS):
            # Capability only — do not promote LLM. Real COVERED is coverage_from_report.
            verdict = "PARTIAL" if best == READS else "COVERED"
        elif best in (SOME, READS):
            verdict = "PARTIAL"
        else:
            verdict = "GAP"
        rows.append({**c, "best": best, "verdict": verdict})
    return rows


_BMC_UB = {
    "INT-SIGNED-OVF", "INT-DIV-ZERO", "INT-SHIFT-UB",
    "MEM-OOB-READ", "MEM-OOB-WRITE",
}

# The pir stage encodes these on every function it closes (docs/PIR.md
# "Properties"): signed overflow, division, shifts, reads of uninitialised
# promotable locals, clz/ctz of zero. Memory is not encoded (pointer
# parameters are NEEDS-HARNESS), so MEM-OOB-* are not folded for pir.
_PIR_UB = {
    "INT-SIGNED-OVF", "INT-DIV-ZERO", "INT-SHIFT-UB", "UNINIT-READ", "INT-CLZ-ZERO",
}

_RANK = {PROVES: 3, FINDS: 2, SOME: 1, READS: 1}


def coverage_from_report(report) -> list[dict]:
    """COVERED only if a finding of that class actually reached PROVES or FINDS.

    The LLM is READS and never COVERED. HYPOTHESIS/READS never promote COVERED.
    A skipped/NOTRUN stage does not invent coverage. BMC PROVED-* without a
    class still discharges the encoded UB properties for functions it closed.
    WP/contracts PROVED-ASSUMING is PROVES for FUNC-CONTRACT only — never
    folded into BMC PROVED / encoded UB.
    """
    from prism import laws

    hits: dict[str, str] = {}
    bmc_closed = False
    pir_closed = False
    ran_ok = {s.name for s in report.stages if s.status == "ok"}
    contract_stages = {"wp", "contracts"}

    def note(cls: str, strength: str) -> None:
        if not cls or strength not in _RANK:
            return
        if strength == READS:
            prev = hits.get(cls)
            if prev is None:
                hits[cls] = READS
            return
        prev = hits.get(cls)
        if prev is None or _RANK[strength] > _RANK[prev]:
            hits[cls] = strength

    for s in report.stages:
        for f in s.findings:
            if s.name == "llm" or f.status in {laws.HYPOTHESIS, laws.READS}:
                note(f.cls or "INTENT", READS)
                continue
            if f.status == laws.ERROR and f.cls and (f.strength or "") == FINDS:
                note(f.cls, FINDS)
                continue
            if f.status in {laws.NOTRUN, laws.CLEAN, laws.ERROR, laws.NEEDS_HARNESS,
                            laws.TIMEOUT, laws.UNKNOWN, laws.NOSEED}:
                continue
            if laws.is_proof(f.status):  # incl. PROVED-CERTIFIED
                # WP/contracts stay PROVED-ASSUMING; only BMC folds encoded UB.
                if s.name == "bmc":
                    bmc_closed = True
                if s.name == "pir":
                    pir_closed = True
                cls = f.cls or ("FUNC-CONTRACT" if s.name in contract_stages else "")
                st = f.strength if f.strength in _RANK else PROVES
                if not f.strength:
                    st = PROVES
                note(cls, st)
                continue
            if f.status in {laws.FAILED, laws.CRASH, laws.BOUNDED}:
                st = f.strength if f.strength in _RANK else FINDS
                if f.status == laws.BOUNDED:
                    st = SOME
                note(f.cls, st)

    if bmc_closed:
        for cid in _BMC_UB:
            hits.setdefault(cid, PROVES)
    if pir_closed:
        for cid in _PIR_UB:
            hits.setdefault(cid, PROVES)

    rows = []
    for c in CLASSES:
        cid = c["id"]
        best = hits.get(cid)
        if best in (PROVES, FINDS):
            verdict = "COVERED"
        elif best in (SOME, READS):
            verdict = "PARTIAL"
        else:
            capable = [inst for inst in c["seen"] if inst in ran_ok]
            if capable and any(c["seen"][i] == READS for i in capable) and all(
                c["seen"][i] == READS for i in capable
            ):
                best = READS
                verdict = "PARTIAL"
            elif capable:
                best = SOME
                verdict = "PARTIAL"
            else:
                verdict = "GAP"
        rows.append({**c, "best": best, "verdict": verdict})
    return rows
