// Table-driven doctests for prism::run_bmc (declared in prism/stages.hpp).
// Ports the testdata oracle rows from tests/test_bmc.py TestBMC and k-induction
// extras from TestKInduction. Generated by tools/gen_test_bmc_cpp.py.

#include <doctest/doctest.h>
#ifdef ERROR
#  undef ERROR
#endif

#include "prism/cparse.hpp"
#include "prism/laws.hpp"
#include "prism/models.hpp"
#include "prism/stages.hpp"

#include <algorithm>
#include <filesystem>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

namespace {

namespace fs = std::filesystem;
namespace laws = prism::laws;

fs::path td_root() { return fs::path(PRISM_SOURCE_DIR) / "testdata"; }

using Names = std::vector<std::string_view>;

prism::FunctionInfo load_fn(std::string_view file, std::string_view name) {
    auto p = td_root() / file;
    for (auto& f : prism::extract_functions(p, p.string()))
        if (f.name == name) return f;
    FAIL("missing " << name << " in " << file);
    return {};
}

prism::Finding bmc_one(const prism::FunctionInfo& fn, int unwind = 8) {
    auto recs = prism::run_bmc({fn}, unwind);
    REQUIRE(recs.size() == 1);
    return recs[0];
}

bool one_of(std::string_view s, const Names& xs) {
    return std::find(xs.begin(), xs.end(), s) != xs.end();
}

std::string extra_get(const prism::Finding& f, std::string_view key) {
    auto it = f.extra.find(std::string(key));
    return it == f.extra.end() ? std::string() : it->second;
}

const Names kProof = {laws::PROVED, laws::PROVED_UNBOUNDED};
const Names kProofOrBounded = {laws::PROVED, laws::PROVED_UNBOUNDED, laws::BOUNDED};
const Names kFsmOk = {laws::FAILED, laws::PROVED, laws::PROVED_UNBOUNDED, laws::BOUNDED};

struct BmcRow {
    std::string_view id;
    std::string_view file;
    std::string_view func;
    std::string_view exact_status;
    Names allow_status;
    Names forbid_status;
    std::string_view exact_cls;
    Names allow_cls;
    bool counterexample = false;
    std::vector<std::pair<std::string_view, std::string_view>> extra;
};

const std::vector<BmcRow>& bmc_rows() {
    static const std::vector<BmcRow> rows = {
                {"overflow", "add_overflow.c", "add_overflow", laws::FAILED, {}, {laws::ERROR, laws::NOTRUN}, "INT-SIGNED-OVF", {}, true, {{"incremental_k", "1"}, {"param_premise", "named"}}},
{"div0", "div_param.c", "div_param", laws::FAILED, {}, {laws::ERROR}, "INT-DIV-ZERO", {}, false, {}},
{"oob", "oob_write.c", "oob_write", laws::FAILED, {}, {laws::ERROR}, {}, {"MEM-OOB-WRITE", "MEM-OOB-READ"}, false, {}},
{"abs", "abs_ok.c", "abs_ok", {}, kProof, {laws::ERROR, laws::NEEDS_HARNESS}, {}, {}, false, {}},
{"fsm", "fsm.c", "fsm_step", {}, kFsmOk, {laws::ERROR}, {}, {}, false, {}},
{"masked_switch", "masked_switch.c", "masked_switch", {}, kFsmOk, {laws::ERROR}, {}, {}, false, {}},
{"loop_prove", "loop_prove.c", "loop_prove", {}, kProof, {laws::ERROR}, {}, {}, false, {}},
{"loop_overflow", "loop_overflow.c", "loop_overflow", laws::FAILED, {}, {laws::ERROR}, "INT-SIGNED-OVF", {}, false, {}},
{"taut_bound_ok", "taut_bound.c", "taut_bound_ok", {}, kProofOrBounded, {laws::ERROR}, {}, {}, false, {}},
{"do_once", "subset.c", "do_once", {}, kProof, {laws::ERROR}, {}, {}, false, {}},
{"do_overflow", "subset.c", "do_overflow", laws::FAILED, {}, {laws::ERROR}, "INT-SIGNED-OVF", {}, false, {}},
{"sizeof_int", "subset.c", "sz_int", {}, kProof, {laws::ERROR}, {}, {}, false, {}},
{"sizeof_arr", "subset.c", "sz_arr", {}, kProof, {laws::ERROR}, {}, {}, false, {}},
{"ternary_pick", "subset.c", "pick", {}, kProof, {laws::ERROR}, {}, {}, false, {}},
{"ternary_abs_ovf", "subset.c", "abs_ter", laws::FAILED, {}, {laws::ERROR}, "INT-SIGNED-OVF", {}, false, {}},
{"trunc_ok", "trunc.c", "trunc_ok", {}, kProof, {laws::ERROR}, {}, {}, false, {}},
{"trunc_bad", "trunc.c", "trunc_bad", {}, {}, {laws::ERROR}, {}, {}, false, {}},
{"continue_skip", "continue.c", "cont_skip", {}, kProof, {laws::FAILED, laws::ERROR}, {}, {}, false, {}},
{"comma_sum", "comma.c", "comma_sum", {}, kProof, {laws::ERROR}, {}, {}, false, {}},
{"comma_ovf", "comma.c", "comma_ovf", laws::FAILED, {}, {laws::ERROR}, "INT-SIGNED-OVF", {}, false, {}},
{"goto_unstructured", "goto_structured.c", "goto_into_block", laws::NEEDS_HARNESS, {}, {laws::PROVED, laws::PROVED_UNBOUNDED, laws::BOUNDED}, {}, {}, false, {}},
{"unsigned_add_wrap", "unsigned.c", "add_u", {}, kProof, {laws::FAILED, laws::ERROR}, {}, {}, false, {}},
{"unsigned_idx_ok", "unsigned.c", "idx_u_ok", {}, kProof, {laws::ERROR}, {}, {}, false, {}},
{"unsigned_idx_bad", "unsigned.c", "idx_u_bad", laws::FAILED, {}, {laws::ERROR}, {}, {"MEM-OOB-READ", "MEM-OOB-WRITE"}, false, {}},
{"unsigned_dead", "unsigned.c", "dead_u", {}, kProof, {laws::FAILED, laws::ERROR}, {}, {}, false, {}},
{"vla_bad", "vla.c", "vla_bad", laws::NEEDS_HARNESS, {}, {laws::PROVED, laws::PROVED_UNBOUNDED, laws::BOUNDED}, {}, {}, false, {}},
{"vla_ok", "vla.c", "vla_ok", {}, kProofOrBounded, {laws::NEEDS_HARNESS, laws::ERROR}, {}, {}, false, {}},
{"nested_ovf", "nested.c", "nested_ovf", laws::FAILED, {}, {laws::ERROR}, "INT-SIGNED-OVF", {}, false, {{"k_induction", "not-needed"}}},
{"nested_ok", "nested.c", "nested_ok", {}, kProofOrBounded, {laws::ERROR, laws::FAILED}, {}, {}, false, {}},
{"long_long_ovf", "longlong.c", "add_ll", laws::FAILED, {}, {laws::ERROR}, "INT-SIGNED-OVF", {}, false, {}},
{"long_long_ok", "longlong.c", "add_ll_ok", {}, kProof, {laws::ERROR}, {}, {}, false, {}},
{"cxx_move", "use_after_move.cpp", "move_bad", laws::NEEDS_HARNESS, {}, {laws::ERROR}, {}, {}, false, {}},
{"kinduct_closed", "kinduct.c", "kinduct_closed", laws::PROVED_UNBOUNDED, {}, {laws::ERROR, laws::FAILED}, {}, {}, false, {{"k_induction", "closed"}, {"k_induction_k", "1"}}},
{"kinduct_step_open", "kinduct.c", "kinduct_step_open", laws::BOUNDED, {}, {laws::FAILED, laws::ERROR}, {}, {}, false, {{"k_induction_tried", "1"}}},
{"unchecked_alloc", "unchecked_alloc.c", "unchecked_alloc", laws::NEEDS_HARNESS, {}, {laws::ERROR}, {}, {}, false, {}},
{"esc_bad", "stack_escape.c", "esc_bad", laws::NEEDS_HARNESS, {}, {laws::ERROR}, {}, {}, false, {}},
{"arr_esc_bad", "stack_escape.c", "arr_esc_bad", laws::NEEDS_HARNESS, {}, {laws::PROVED, laws::PROVED_UNBOUNDED, laws::BOUNDED, laws::FAILED, laws::ERROR}, {}, {}, false, {}},
    };
    return rows;
}

void check_row(const BmcRow& row) {
    INFO("row " << row.id << " " << row.file << ":" << row.func);
    auto fn = load_fn(row.file, row.func);
    auto r = bmc_one(fn);
    CHECK(r.function == row.func);
    CHECK(r.stage == "bmc");
    if (!row.exact_status.empty()) {
        CHECK_MESSAGE(r.status == row.exact_status, r.status << " " << r.message);
    } else if (!row.allow_status.empty()) {
        CHECK_MESSAGE(one_of(r.status, row.allow_status), r.status << " " << r.message);
    }
    for (auto bad : row.forbid_status) CHECK_MESSAGE(r.status != bad, r.status << " " << r.message);
    if (!row.exact_cls.empty()) CHECK(r.cls == row.exact_cls);
    else if (!row.allow_cls.empty()) CHECK_MESSAGE(one_of(r.cls, row.allow_cls), r.cls << " " << r.message);
    if (row.counterexample) CHECK_FALSE(r.counterexample.empty());
    for (auto [k, v] : row.extra)
        CHECK_MESSAGE(extra_get(r, k) == v, k << "=" << extra_get(r, k) << " expected " << v);
    if (row.id == "goto_unstructured") CHECK(r.message.find("goto") != std::string::npos);
}

}  // namespace

TEST_CASE("bmc: missing Z3 is NOTRUN, never a proof or clean") {
#ifndef PRISM_HAS_Z3
    prism::FunctionInfo fn;
    fn.file = "abs_ok.c";
    fn.name = "abs_ok";
    fn.kind = "SCALAR";
    fn.line = 1;
    fn.signature = "int abs_ok(int x)";
    fn.params = {"int", "x"};
    fn.body = "return x < 0 ? -x : x;";
    auto recs = prism::run_bmc({fn}, 8);
    REQUIRE(recs.size() == 1);
    CHECK(recs[0].status == std::string(laws::NOTRUN));
    CHECK(recs[0].status != std::string(laws::CLEAN));
    CHECK(recs[0].status != std::string(laws::PROVED));
    CHECK_FALSE(laws::is_proof(recs[0].status));
    CHECK(recs[0].message.find("z3") != std::string::npos);
    CHECK(extra_get(recs[0], "install").find("PRISM_Z3") != std::string::npos);
#else
    MESSAGE("PRISM_HAS_Z3: skip NOTRUN row");
#endif
}

#ifdef PRISM_HAS_Z3
TEST_CASE("bmc: testdata table (run_bmc)") {
    const auto& rows = bmc_rows();
    REQUIRE(rows.size() >= 15);
    for (const auto& row : rows) check_row(row);
}

TEST_CASE("run_bmc never silent-empty on a function list") {
    auto fn = load_fn("abs_ok.c", "abs_ok");
    auto recs = prism::run_bmc({fn}, 8);
    REQUIRE_FALSE(recs.empty());
    CHECK(recs[0].function == "abs_ok");
    auto empty = prism::run_bmc({}, 8);
    CHECK(empty.empty());
}
#endif

// tests/test_unencoded_contract.py: strcpy/strcat stay BMC-only; designated init gate.
TEST_CASE("bmc unencoded: strcpy and strcat are not syntax gaps") {
    prism::FunctionInfo scalar;
    scalar.file = "x.c";
    scalar.name = "f";
    scalar.kind = "SCALAR";
    scalar.line = 1;
    scalar.signature = "int f(int n)";
    scalar.params = {{"int", "n"}};
    for (auto [name, body] : std::vector<std::pair<const char*, const char*>>{
             {"strcpy_only", "strcpy(d, s); return n;"},
             {"strcat_only", "strcat(d, s); return n;"},
             {"sprintf_only", "sprintf(d, \"%d\", n); return n;"},
         }) {
        scalar.name = name;
        scalar.body = body;
        CHECK_FALSE(prism::unencoded_syntax_reason_cached(scalar, "bitvector BMC"));
    }
    auto copy = load_fn("unbounded_copy.c", "copy_bad");
    CHECK(copy.body.find("strcpy") != std::string::npos);
    CHECK_FALSE(prism::unencoded_syntax_reason_cached(copy, "bitvector BMC"));
    auto cat = load_fn("unbounded_copy.c", "cat_bad");
    CHECK(cat.body.find("strcat") != std::string::npos);
    CHECK_FALSE(prism::unencoded_syntax_reason_cached(cat, "bitvector BMC"));
}

TEST_CASE("bmc unencoded: strlcpy is named; plain goto is encoded") {
    prism::FunctionInfo scalar;
    scalar.file = "x.c";
    scalar.name = "sl";
    scalar.kind = "SCALAR";
    scalar.line = 1;
    scalar.signature = "int sl(int n)";
    scalar.params = {{"int", "n"}};
    scalar.body = "strlcpy(d, s, 4); return n;";
    auto syn = prism::unencoded_syntax_reason_cached(scalar, "bitvector BMC");
    REQUIRE(syn.has_value());
    CHECK(syn->find("strlcpy") != std::string::npos);
    CHECK(syn->find("strcpy") == std::string::npos);
    auto desig_ok = load_fn("designated_init.c", "desig_assign_ok");
    CHECK_FALSE(prism::unencoded_syntax_reason_cached(desig_ok, "bitvector BMC"));
    auto desig_bad = load_fn("designated_init.c", "desig_init_bad");
    auto bad_syn = prism::unencoded_syntax_reason_cached(desig_bad, "bitvector BMC");
    REQUIRE(bad_syn.has_value());
    CHECK(bad_syn->find("designated init") != std::string::npos);
    auto goto_fn = load_fn("goto_unenc.c", "with_goto");
    CHECK_FALSE(prism::unencoded_syntax_reason_cached(goto_fn, "bitvector BMC"));
    auto computed = load_fn("computed_goto.c", "computed_goto_bad");
    auto cg = prism::unencoded_syntax_reason_cached(computed, "bitvector BMC");
    REQUIRE(cg.has_value());
    CHECK(cg->find("computed goto") != std::string::npos);
}
