// Table-driven doctests for prism::run_concolic (src/prism/stages/concolic.cpp).
// Ports tests/test_concolic.py planted bugs, semantic harness gates, and unenc corpus.
// Generated by tools/gen_test_concolic_cpp.py — regenerate after Python test changes.

#include <doctest/doctest.h>
#ifdef ERROR
#  undef ERROR
#endif

#include "prism/cparse.hpp"
#include "prism/laws.hpp"
#include "prism/models.hpp"
#include "prism/stages.hpp"

#include <algorithm>
#include <filesystem>
#include <map>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

namespace {

namespace fs = std::filesystem;
namespace laws = prism::laws;

fs::path td_root() { return fs::path(PRISM_SOURCE_DIR) / "testdata"; }

std::pair<prism::FunctionInfo, fs::path> fn_named(const std::string& name) {
    static std::map<std::string, std::pair<prism::FunctionInfo, fs::path>> cache = [] {
        std::map<std::string, std::pair<prism::FunctionInfo, fs::path>> m;
        for (auto& e : fs::directory_iterator(td_root())) {
            auto ext = e.path().extension();
            if (ext != ".c" && ext != ".cpp") continue;
            for (auto& f : prism::extract_functions(e.path(), e.path().string()))
                m.emplace(f.name, std::make_pair(f, e.path()));
        }
        return m;
    }();
    auto it = cache.find(name);
    REQUIRE_MESSAGE(it != cache.end(), name);
    return it->second;
}

prism::FunctionInfo load_fn(std::string_view name) { return fn_named(std::string(name)).first; }

prism::Finding concolic_one(const prism::FunctionInfo& fn, int budget) {
    auto recs = prism::run_concolic({fn}, budget);
    REQUIRE(recs.size() == 1);
    return recs[0];
}

using Names = std::vector<std::string_view>;

bool one_of(std::string_view s, const Names& xs) {
    return std::find(xs.begin(), xs.end(), s) != xs.end();
}

const Names kForbidNeedHarness = {laws::ERROR, laws::CLEAN, laws::CRASH, laws::PROVED, laws::PROVED_UNBOUNDED,
                                  laws::BOUNDED};
const Names kForbidFlexible = {laws::NEEDS_HARNESS, laws::ERROR, laws::PROVED, laws::PROVED_UNBOUNDED, laws::BOUNDED};
const Names kForbidCrashPlant = {laws::PROVED, laws::PROVED_UNBOUNDED, laws::PROVED_ASSUMING, laws::ERROR};
const Names kForbidClean = {laws::ERROR, laws::PROVED, laws::PROVED_UNBOUNDED, laws::PROVED_ASSUMING};
const Names kForbidGoto = {laws::NEEDS_HARNESS, laws::PROVED, laws::PROVED_UNBOUNDED, laws::BOUNDED, laws::CLEAN};
const Names kForbidOnlyCrash = {laws::CRASH};
const Names kAllowOobCls = {"MEM-OOB-READ", "MEM-OOB-WRITE"};

struct ConcolicRow {
    std::string_view func;
    int budget;
    std::string_view exact_status;
    Names forbid_status;
    std::string_view exact_cls;
    Names allow_cls;
    bool counterexample;
    bool message_not_proof;
};

void check_row(const ConcolicRow& row) {
    INFO("concolic " << row.func << " budget=" << row.budget);
    auto fn = load_fn(row.func);
    auto r = concolic_one(fn, row.budget);
    CHECK(r.stage == "concolic");
    CHECK(r.function == row.func);
    if (!row.exact_status.empty())
        CHECK_MESSAGE(r.status == row.exact_status, r.status << " " << r.message);
    for (auto bad : row.forbid_status) CHECK_MESSAGE(r.status != bad, r.status << " " << r.message);
    if (!row.exact_cls.empty()) CHECK(r.cls == row.exact_cls);
    if (!row.allow_cls.empty()) CHECK_MESSAGE(one_of(r.cls, row.allow_cls), r.cls << " " << r.message);
    if (row.counterexample) CHECK_FALSE(r.counterexample.empty());
    if (row.message_not_proof) CHECK(r.message.find("not a proof") != std::string::npos);
    if (row.exact_status == laws::CRASH) {
        CHECK(r.strength == laws::STRENGTH_FINDS);
        CHECK_FALSE(laws::is_proof(r.status));
    }
    if (row.exact_status == laws::CLEAN) CHECK_FALSE(laws::is_proof(r.status));
}


const std::vector<ConcolicRow>& planted_rows() {
    static const std::vector<ConcolicRow> rows = {
        {"add_overflow", 32, "CRASH", kForbidClean, "INT-SIGNED-OVF", {}, true, false},
        {"div_param", 32, "CRASH", kForbidClean, "INT-DIV-ZERO", {}, true, false},
        {"oob_write", 32, "CRASH", kForbidClean, "MEM-OOB-WRITE", {}, true, false},
        {"shift_ub", 32, "CRASH", kForbidClean, "INT-SHIFT-UB", {}, true, false},
    };
    return rows;
}

const std::vector<ConcolicRow>& key_rows() {
    static const std::vector<ConcolicRow> rows = {
        {"null_branch", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"unchecked_alloc", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"arr_esc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"vla_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"fdiv_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"rec_id", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"with_goto", 8, "ERROR", kForbidGoto, {}, {}, false, false},
        {"taut_bound_bad", 8, {}, kForbidFlexible, {}, {}, false, false},
        {"copy_bad", 8, "CRASH", kForbidClean, "MEM-OOB-WRITE", {}, false, false},
        {"trunc_ok", 8, "CLEAN", kForbidClean, {}, {}, false, true},
        {"alloca_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"alloca_ok", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"jmp_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"jmp_ok", 8, "CLEAN", kForbidClean, {}, {}, false, true},
        {"arr_esc_plus0", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"arr_esc_plus_rhs", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"atom_qual_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"lock_init_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"vol_ok", 8, {}, kForbidFlexible, {}, {}, false, false},
        {"asm_nop", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"generic_sel", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"const_local_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"const_param_ok", 8, {}, kForbidFlexible, {}, {}, false, false},
        {"empty_inf_ok", 8, {}, kForbidFlexible, {}, {}, false, false},
        {"struct_local_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"typedef_local_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"arr_esc_paren", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"esc_paren_addr", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"register_local_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"auto_type_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"auto_type_gnu_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"static_local_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"extern_local_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"anon_enum_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"enum_const_ok", 8, "CLEAN", kForbidClean, {}, {}, false, true},
        {"alignas_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"compound_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"const_for_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"anon_struct_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"missing_nul_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"mkstemp_ok", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"mkstemp_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"percent_n_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"tls_local_ok", 8, {}, kForbidFlexible, {}, {}, false, false},
        {"complex_ok", 8, {}, kForbidFlexible, {}, {}, false, false},
        {"sizeof_ok", 8, {}, kForbidFlexible, {}, {}, false, false},
        {"nested_fn_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"nested_fn_ok", 8, {}, kForbidFlexible, {}, {}, false, false},
        {"desig_init_ok", 8, {}, kForbidFlexible, {}, {}, false, false},
        {"static_assert_ok", 8, {}, kForbidFlexible, {}, {}, false, false},
        {"alignof_ok", 8, {}, kForbidFlexible, {}, {}, false, false},
        {"va_arg_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"va_arg_ok", 8, {}, kForbidFlexible, {}, {}, false, false},
        {"range_for_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"range_for_ok", 8, {}, kForbidFlexible, {}, {}, false, false},
        {"lambda_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"lambda_ok", 8, {}, kForbidFlexible, {}, {}, false, false},
        {"static_cast_ok", 8, {}, kForbidFlexible, {}, {}, false, false},
        {"packed_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"packed_ok", 8, {}, kForbidFlexible, {}, {}, false, false},
        {"coro_await_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"coro_ok", 8, {}, kForbidFlexible, {}, {}, false, false},
        {"label_addr_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"wide_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"wide_ok", 8, {}, kForbidFlexible, {}, {}, false, false},
        {"bitfield_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"bitfield_ok", 8, {}, kForbidFlexible, {}, {}, false, false},
        {"popen_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"popen_ok", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"tls_local_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"thread_local_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"complex_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"imaginary_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"complex_float_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"typeof_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"typeof_gnu_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"computed_goto_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"computed_goto_ptr_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"desig_init_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"desig_field_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"alignof_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"alignof_gnu_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"dyn_cast_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"typeid_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"reinterp_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"spawn_fork_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"spawn_exec_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"throws_not_dtor", 8, {}, {}, {}, {}, false, false},
        {"try_ok", 8, {}, {}, {}, {}, false, false},
        {"saturate", 8, "CLEAN", kForbidClean, {}, {}, false, true},
        {"abs_ok", 8, "CLEAN", kForbidClean, {}, {}, false, true},
        {"add_u", 8, "CLEAN", kForbidClean, {}, {}, false, true},
        {"idx_u_ok", 8, "CLEAN", kForbidClean, {}, {}, false, true},
        {"idx_u_bad", 8, "CRASH", {}, {}, kAllowOobCls, false, false},
        {"add_ll", 8, {}, kForbidOnlyCrash, {}, {}, false, false},
    };
    return rows;
}

const std::vector<ConcolicRow>& unenc_rows() {
    static const std::vector<ConcolicRow> rows = {
        {"acct_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"add_key_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"addrinfo_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"addrof_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"addsat_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"adjtime_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"adjtimex_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"adjv_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"aflag_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"aio_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"aligned_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"any_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"apply_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"arc4random_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"arch_prctl_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"array_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"asconst_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"asmalign_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"asrval_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"assume_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"async_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"atomic_builtin_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"atomic_ref_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"audit_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"barrier_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"bciter_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"binsem_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"bitcast_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"bitceil_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"bitset_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"bitw_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"bpf_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"byteswap_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"bzero_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"cachestat_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"call_once_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"cap_enter_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"cap_fcntls_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"cap_getmode_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"cap_getrights_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"cap_rights_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"cap_sandboxed_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"capset_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"cart_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"case_range_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"chflags_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"choose_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"chrono_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"chunk_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"clamp_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"cleanup_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"clock_set_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"clock_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"clone3_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"clone_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"close_range_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"closefrom_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"clz_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"cmpl_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"condvar_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"connect_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"constexpr_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"construct_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"copyable_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"coro_h_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"corrm_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"countl_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"countv_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"cpuclock_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"cpuset_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"crypt_newhash_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"curexc_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"cvany_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"daemon_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"decimal_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"deque_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"destroyn_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"devname_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"dlfunc_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"dlopen_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"dropv_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"dup_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"dwhile_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"eaccess_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"elems_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"embed_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"endian_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"enumv_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"epoll_create_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"epoll_pwait_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"errc_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"errcat_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"eventfd_rw_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"exc_ptr_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"exch_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"execution_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"execveat_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"expected_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"exscan_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"extattr_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"faccessat2_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"faccessat_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"fadvise_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"fallocate_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"fanotify_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"fchmodat2_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"fchmodat_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"fcntl_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"fence_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"fflags_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"fhlink_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"file_getattr_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"filterv_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"flat_map_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"flat_mmap_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"flat_mset_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"flat_set_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"float16_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"flock_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"fmemopen_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"fmtto_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"fn_ref_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"fold_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"format_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"frange_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"from_chars_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"fs_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"fseek_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"fsopen_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"fstatat_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"fstream_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"fsync_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"fts_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"function_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"futex2_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"futex_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"futex_waitv_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"fwd_list_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"fwdlike_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"gcd_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"generator_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"getbootfile_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"getcpu_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"getdents_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"getdirentries_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"getdomainname_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"getfh_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"getfsent_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"getfsstat_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"getgrnam_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"getgrouplist_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"getgroups_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"getline_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"getlogin_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"getmntinfo_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"getopt_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"getosreldate_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"getpagesize_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"getpagesizes_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"getpass_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"getpeereid_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"getpriority_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"getprogname_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"getrandom_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"getresuid_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"getrusage_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"getsockname_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"getsockopt_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"gettid_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"getvfsbyname_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"glob_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"hazard_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"hive_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"ice_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"ifcx_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"import_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"indirect_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"inet_pton_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"init_module_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"initgroups_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"inotify_rm_watch_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"inotify_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"inscan_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"int128_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"invoke_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"io_setup_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"io_submit_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"ioperm_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"ioprio_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"iota_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"iouring_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"isatty_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"issetugid_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"jail_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"join_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"jthread_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"jwith_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"kcmp_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"kenv_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"kevent_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"kexec_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"keyctl_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"keys_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"kill_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"killdep_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"kinfo_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"kld_isloaded_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"kldfirstmod_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"kldload_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"klogctl_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"kqueue_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"ksem_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"ktrace_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"kvm_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"landlock_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"latch_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"launder_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"layoutc_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"lcm_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"lerp_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"lifetime_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"linalg_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"linkat_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"lio_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"list_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"listen_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"listmount_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"login_class_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"loginclass_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"lpathconf_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"lsm_attr_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"mac_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"map_shadow_stack_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"map_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"mbind_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"mdspan_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"membarrier_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"memfd_secret_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"memfd_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"mempolicy_home_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"midpt_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"mincore_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"minherit_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"mkdirat_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"mkeptr_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"mknodat_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"mlock2_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"mlock_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"mmap_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"modfind_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"mount_setattr_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"mount_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"move_pages_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"mq_open_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"mq_unlink_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"mseal_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"mset_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"msgctl_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"msgget_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"msgsnd_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"msync_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"multimap_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"mutex_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"name_to_handle_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"nested_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"nexit_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"nfssvc_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"nftw_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"nice_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"nmount_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"nontype_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"ntp_gettime_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"nullptr_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"open_tree_attr_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"openat2_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"openat_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"opendir_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"osync_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"out_ptr_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"packaged_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"pause_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"pdfork_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"pdgetpid_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"perf_event_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"personality_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"pidfd_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"pinter_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"pipe_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"pivot_root_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"pkey_free_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"pkey_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"pledge_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"pmr_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"ppoll_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"pqueue_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"prctl_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"preadv_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"prlimit_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"procctl_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"process_madvise_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"process_mrelease_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"process_vm_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"pthcpuclock_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"pthread_atfork_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"pthread_attr_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"pthread_barrier_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"pthread_cancel_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"pthread_cond_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"pthread_key_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"pthread_kill_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"pthread_sigmask_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"pthread_yield_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"ptsname_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"qexit_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"queue_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"quotactl_fd_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"quotactl_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"ranges_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"rcu_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"readahead_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"readlinkat_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"reallocarray_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"reallocf_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"reboot_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"reduce_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"refwrap_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"regex_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"remap_file_pages_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"renameat2_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"renameat_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"repeat_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"request_key_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"requires_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"restrict_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"revoke_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"rfork_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"rmutex_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"rotl_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"rseq_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"rtmutex_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"rto_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"rtprio_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"rview_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"rwlock_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"sbrk_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"scenum_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"sched_setattr_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"sched_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"sched_yield_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"schedprio_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"seccomp_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"select_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"sem_open_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"sem_timedwait_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"sem_trywait_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"sem_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"semctl_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"semget_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"semop_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"send_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"sendfile_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"sendmmsg_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"sendmsg_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"set_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"setdomainname_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"setfib_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"setfsuid_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"sethostname_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"setitimer_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"setlogin_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"setpgid_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"setreuid_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"setrlimit_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"setsched_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"setterm_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"settimeofday_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"setxattr_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"setxattrat_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"shm_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"shmat_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"shmctl_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"shmget_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"sigaction_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"sigaltstack_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"signalfd_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"sigprocmask_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"sigqueue_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"sigqueueinfo_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"sigwait_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"simd_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"sleep_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"slide_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"slock_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"socketpair_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"source_loc_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"spaceship_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"spanstream_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"spawn_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"spawnattr_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"spin_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"splice_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"stack_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"stacktrace_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"stat_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"statfs_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"statx_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"stmutex_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"stop_token_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"stride_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"strlcpy_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"strmode_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"strtonum_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"swapon_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"symlinkat_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"sync_file_range_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"syncbuf_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"syncfs_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"sysarch_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"sysconf_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"sysctl_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"syserr_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"sysinfo_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"syslog_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"takev_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"task_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"tcgetattr_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"text_enc_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"tgkill_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"thr_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"timer_create_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"timer_delete_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"timer_settime_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"timerfd_settime_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"timingsafe_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"tkill_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"tmutex_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"to_chars_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"to_under_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"toaddr_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"toarr_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"tred_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"tscan_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"tthread_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"tuple_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"tview_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"twhile_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"typedmem_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"typeid_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"typeof_unqual_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"tzdb_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"u8_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"ucontext_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"uicopy_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"uifill_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"umap_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"ummap_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"umset_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"umtx_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"uname_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"uncaught_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"unexpect_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"unlinkat_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"unmount_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"unreach_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"unveil_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"userfaultfd_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"uset_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"ustat_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"utimensat_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"uuidgen_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"uvalue_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"valarray_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"valloc_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"vals_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"vecsize_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"vhangup_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"visit_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"vjoin_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"vzip_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"wait4_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"wait6_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"waitpid_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"wconv_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"wcs_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"weak_ptr_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"wordexp_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"wstring_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"zoned_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
        {"ztrans_unenc_bad", 8, "NEEDS-HARNESS", kForbidNeedHarness, {}, {}, false, false},
    };
    return rows;
}

}  // namespace

TEST_CASE("concolic: planted bugs crash with counterexample") {
    for (const auto& row : planted_rows()) check_row(row);
}

TEST_CASE("concolic: semantic and harness gates (testdata)") {
    const auto& rows = key_rows();
    REQUIRE(rows.size() >= 40);
    for (const auto& row : rows) check_row(row);
}

TEST_CASE("concolic: unencoded libc/C++ plants are NEEDS-HARNESS") {
    const auto& rows = unenc_rows();
    REQUIRE(rows.size() >= 100);
    for (const auto& row : rows) check_row(row);
}

#ifdef PRISM_HAS_Z3
TEST_CASE("concolic: KLEE fork negated branch finds div-zero") {
    auto fn = load_fn("klee_fork_neg");
    auto r = concolic_one(fn, 32);
    CHECK(r.status == std::string(laws::CRASH));
    CHECK(r.cls == "INT-DIV-ZERO");
    CHECK(r.extra.at("oracle") == "z3");
    CHECK(std::stoi(r.extra.at("z3_seeds")) > 0);
}

TEST_CASE("concolic: unsat branch skipped when Z3 available") {
    auto fn = load_fn("klee_fork_unsat");
    auto r = concolic_one(fn, 32);
    CHECK(r.status == std::string(laws::CLEAN));
    CHECK(std::stoi(r.extra.at("skipped_unsat")) > 0);
}
#endif

TEST_CASE("concolic: strcat overflow still CRASHes in the oracle") {
    auto fn = load_fn("cat_bad");
    auto r = concolic_one(fn, 8);
    CHECK(r.status == std::string(laws::CRASH));
    CHECK(r.cls == "MEM-OOB-WRITE");
    CHECK(r.status != std::string(laws::NEEDS_HARNESS));
}

TEST_CASE("concolic: run_concolic returns one row per function") {
    auto fn = load_fn("abs_ok");
    auto rs = prism::run_concolic({fn}, 8);
    REQUIRE(rs.size() == 1);
    CHECK(rs[0].function == "abs_ok");
    CHECK(rs[0].stage == "concolic");
    CHECK(prism::run_concolic({}, 8).empty());
}
