"""Generate src/prism/astlint_discard.inc (roadmap 2.8).

The regex lints have a family of "<fn>() return is discarded" rules
(lint_discarded* calls in src/prism/checkers_*.cpp, each one line-regex
`^\\s*name(...);$` and one taxonomy class). The Clang-AST layer ports the
whole family as one check on the AST (a call that is an expression
statement, to the library function of that name, not the project's own
function), so it needs the callee-name -> class table. This script reads it
out of the regex sources so the two cannot drift.

    python tools/gen_astlint_discard.py            # rewrite the .inc
    python tools/gen_astlint_discard.py --check    # exit 1 when it is stale
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

try:
    import re._constants as sc
    import re._parser as sp
except ImportError:  # Python < 3.11
    import sre_constants as sc  # type: ignore[no-redef]
    import sre_parse as sp  # type: ignore[no-redef]

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "src" / "prism" / "astlint_discard.inc"


def expand(items) -> list[str]:
    """Finite expansions of a parsed regex; a trailing '*' marks a \\w+ tail."""
    outs = [""]
    for op, av in items:
        if op == sc.LITERAL:
            outs = [o + chr(av) for o in outs]
        elif op == sc.SUBPATTERN:
            sub = expand(av[-1])
            outs = [o + s for o in outs for s in sub]
        elif op == sc.BRANCH:
            alts: list[str] = []
            for b in av[1]:
                alts += expand(b)
            outs = [o + s for o in outs for s in alts]
        elif op == sc.IN:
            chars = [chr(v) for k, v in av if k == sc.LITERAL]
            if len(chars) != len(av):
                raise ValueError("character class")
            outs = [o + c for o in outs for c in chars]
        elif op in (sc.MAX_REPEAT, sc.MIN_REPEAT):
            lo, hi, sub = av
            if hi == 1 and lo == 0:
                s2 = expand(sub)
                outs = [o + s for o in outs for s in ["", *s2]]
            elif hi == sc.MAXREPEAT and len(sub) == 1 and sub[0][0] == sc.IN:
                outs = [o + "*" for o in outs]
            else:
                raise ValueError("repeat")
        elif op in (sc.ASSERT_NOT, sc.AT):
            continue
        else:
            raise ValueError(str(op))
    return outs


def table() -> tuple[dict[str, tuple[str, bool]], list[tuple]]:
    rows: list[tuple[str, str, bool]] = []
    skipped: list[tuple] = []
    call = re.compile(r'(lint_discarded(?:_which|_zero|_fn)?)\s*\(\s*funcs,\s*lines,\s*rel,\s*(\w+),\s*"([A-Z0-9-]+)"')
    regex_def = re.compile(r'static\s+(?:const\s+)?Regex\s+(\w+)\s*\(\s*R"\((.*?)\)"\s*\)', re.S)
    shape = re.compile(r"\^\\s\*(?:\\b)?(.*?)\\s\*\\\(\[\^;\]\*\\\)\\s\*;\\s\*\$")
    for f in sorted((ROOT / "src" / "prism").glob("checkers_*.cpp")):
        s = f.read_text(encoding="utf-8")
        defs = [(m.start(), m.group(1), m.group(2)) for m in regex_def.finditer(s)]
        for m in call.finditer(s):
            fn, var, cls = m.groups()
            cands = [d for d in defs if d[1] == var and d[0] < m.start()]
            if not cands:
                skipped.append((var, cls, "no regex"))
                continue
            pat = cands[-1][2]
            pm = shape.fullmatch(pat)
            if not pm:
                skipped.append((var, cls, pat))
                continue
            try:
                names = expand(sp.parse(pm.group(1).replace("(?P<fn>", "(")))
            except ValueError as e:
                skipped.append((var, cls, pat, str(e)))
                continue
            rows += [(n, cls, fn == "lint_discarded_zero") for n in names]
    seen: dict[str, tuple[str, bool]] = {}
    for n, c, z in rows:
        seen.setdefault(n, (c, z))
    return seen, skipped


def render(seen: dict[str, tuple[str, bool]]) -> str:
    out = [
        "// Generated by tools/gen_astlint_discard.py from the regex lints'",
        "// lint_discarded* rules (src/prism/checkers_*.cpp). Do not edit.",
        "// {callee, {class, first argument must be the literal 0}}; a trailing '*'",
        "// matches any suffix.",
    ]
    for n, (c, z) in sorted(seen.items()):
        out.append(f'    {{"{n}", {{"{c}", {"true" if z else "false"}}}}},')
    return "\n".join(out) + "\n"


def main() -> int:
    extra = [a for a in sys.argv[1:] if a != "--check"]
    if extra:
        print(__doc__, file=sys.stderr)
        return 2
    seen, skipped = table()
    text = render(seen)
    for s in skipped:
        print("skipped (not a plain discarded-call rule):", s, file=sys.stderr)
    if "--check" in sys.argv:
        if not OUT.is_file() or OUT.read_text(encoding="utf-8") != text:
            print(f"{OUT} is stale: run python tools/gen_astlint_discard.py", file=sys.stderr)
            return 1
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"{len(seen)} callees, {len(set(c for c, _ in seen.values()))} classes -> {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
