#include "prism/taxonomy.hpp"
#include "prism/laws.hpp"

#include <map>
#include <set>
#include <string>

namespace prism {

const std::vector<TaxonomyClass>& taxonomy_classes() {
    static const std::vector<TaxonomyClass> C = {
        {"MEM-OOB-READ", "out-of-bounds read", {125}, {{"bmc", "PROVES"}, {"esbmc", "PROVES"}, {"fuzz", "FINDS"}, {"concolic", "FINDS"}, {"cppcheck", "FINDS"}, {"lints", "SOME"}}},
        {"MEM-OOB-WRITE", "out-of-bounds write", {787}, {{"bmc", "PROVES"}, {"esbmc", "PROVES"}, {"fuzz", "FINDS"}, {"concolic", "FINDS"}, {"cppcheck", "FINDS"}}},
        {"PTR-NULL-DEREF", "null pointer dereference", {476}, {{"bmc", "PROVES"}, {"lints", "SOME"}, {"cppcheck", "FINDS"}, {"fuzz", "FINDS"}}},
        {"PTR-UNCHECKED-ALLOC", "unchecked allocation", {690}, {{"lints", "FINDS"}, {"cppcheck", "FINDS"}}},
        {"MEM-UAF", "use after free", {416}, {{"lints", "FINDS"}, {"cppcheck", "FINDS"}, {"infer", "FINDS"}}},
        {"MEM-DOUBLE-FREE", "double free", {415}, {{"lints", "FINDS"}, {"cppcheck", "FINDS"}, {"infer", "FINDS"}}},
        {"FMT-STRING", "format string from non-literal", {134}, {{"lints", "FINDS"}, {"taint", "FINDS"}, {"semgrep", "FINDS"}}},
        {"UNINIT-READ", "uninitialised value", {457}, {{"bmc", "SOME"}, {"cppcheck", "FINDS"}, {"lints", "SOME"}}},
        {"UNINIT-SWITCH", "masked switch gap escapes uninit", {}, {{"lints", "FINDS"}}},
        {"INT-SIGNED-OVF", "signed overflow", {190}, {{"bmc", "PROVES"}, {"fuzz", "FINDS"}, {"concolic", "FINDS"}, {"esbmc", "PROVES"}}},
        {"INT-DIV-ZERO", "division by zero", {369}, {{"bmc", "PROVES"}, {"lints", "SOME"}, {"fuzz", "FINDS"}, {"concolic", "FINDS"}, {"cppcheck", "FINDS"}}},
        {"INT-SHIFT-UB", "undefined shift", {1335}, {{"bmc", "PROVES"}, {"lints", "FINDS"}, {"cppcheck", "FINDS"}, {"fuzz", "FINDS"}, {"concolic", "FINDS"}}},
        {"LOCK-IMBALANCE", "lock released on some paths only", {}, {{"lints", "FINDS"}}},
        {"LOCK-ORDER", "conflicting lock acquisition order", {833}, {{"lints", "FINDS"}}},
        {"LOCK-DOUBLE-UNLOCK", "lock released twice without acquire", {765}, {{"lints", "FINDS"}}},
        {"LOCK-DOUBLE-LOCK", "lock acquired twice without release", {764}, {{"lints", "FINDS"}}},
        {"LOCK-MISSING-INIT", "local mutex locked without init", {456, 667}, {{"lints", "FINDS"}}},
        {"CXX-VIRTUAL-IN-CTOR", "virtual call from constructor", {665}, {{"lints", "FINDS"}}},
        {"CXX-SLICING", "derived object passed by value as base", {704}, {{"lints", "FINDS"}}},
        {"CONC-TOCTOU", "check-then-use race on path", {367}, {{"lints", "FINDS"}}},
        {"CONC-ATOMICITY", "non-atomic increment of shared global", {362, 667}, {{"lints", "FINDS"}, {"thread", "SOME"}}},
        {"CXX-EXCEPTION-LEAK", "heap allocation not deleted before throwing call", {401}, {{"lints", "FINDS"}}},
        {"CXX-THROW-DESTRUCTOR", "destructor throws", {248}, {{"lints", "FINDS"}}},
        {"CXX-THROW-SPEC", "dynamic exception specification", {248}, {{"lints", "FINDS"}}},
        {"MEM-REALLOC-SELF", "realloc into own pointer", {401}, {{"lints", "FINDS"}}},
        {"MEM-REALLOC-ZERO", "use after realloc(ptr, 0)", {761, 416}, {{"lints", "FINDS"}}},
        {"MEM-ONESIDED-INDEX", "signed index bounded above only", {125, 787}, {{"lints", "FINDS"}, {"pbsd", "FINDS"}}},
        {"MEM-CAPACITY-FIRST", "capacity grown before allocation earns it", {401, 680}, {{"lints", "FINDS"}, {"pbsd", "FINDS"}}},
        {"MEM-OVERLAP", "memcpy with identical source and destination", {628}, {{"lints", "FINDS"}}},
        {"FUNC-NORETURN", "fatal helper not marked noreturn", {}, {{"lints", "FINDS"}}},
        {"MEM-NOWAIT", "M_NOWAIT allocation without NULL test", {690}, {{"lints", "FINDS"}}},
        {"MEM-MEMSET-SWAP", "memset fill/size arguments swapped", {665}, {{"lints", "FINDS"}, {"spatch", "FINDS"}}},
        {"INT-TAUTOLOGY", "tautological index bound (|| instead of &&)", {571}, {{"lints", "FINDS"}, {"spatch", "FINDS"}}},
        {"INT-BOOL-AS-BIT", "bitwise operator on a comparison", {480}, {{"lints", "FINDS"}}},
        {"INT-WRAP-ALLOC", "allocation size is a wrapping multiply", {190, 680}, {{"lints", "FINDS"}}},
        {"INT-TRUNC", "narrowing integer conversion", {197}, {{"lints", "FINDS"}}},
        {"INT-SIGN-CONV", "signed vs unsigned comparison", {195}, {{"lints", "FINDS"}}},
        {"MEM-NEW-DELETE", "new/delete form mismatch", {762}, {{"lints", "FINDS"}}},
        {"MEM-STACK-ESCAPE", "return pointer to local stack storage", {562}, {{"lints", "FINDS"}}},
        {"STR-UNBOUNDED-COPY", "unbounded string copy into local buffer", {120, 787}, {{"lints", "FINDS"}}},
        {"CTRL-MISSING-RETURN", "value-returning function missing return", {}, {{"lints", "FINDS"}}},
        {"CTRL-FALLTHROUGH", "switch case falls through without annotation", {}, {{"lints", "FINDS"}}},
        {"INT-ENUM-HOLE", "switch on enum missing enumerators", {478}, {{"lints", "FINDS"}}},
        {"CTRL-DEAD-GUARD", "unsigned compared below zero", {571}, {{"lints", "FINDS"}}},
        {"CTRL-EMPTY-INFINITE", "empty infinite loop", {835}, {{"lints", "FINDS"}}},
        {"UNINIT-RETURN", "return of uninitialised local", {457}, {{"lints", "FINDS"}}},
        {"PTR-UNINIT", "dereference of uninitialised local pointer", {457, 824}, {{"lints", "FINDS"}}},
        {"UNINIT-BRANCH", "uninitialised scalar in branch condition", {457}, {{"lints", "FINDS"}}},
        {"STR-OFF-BY-ONE", "string copy leaves no room for NUL", {170}, {{"lints", "FINDS"}}},
        {"STR-MISSING-NUL", "memcpy of a string literal omits the terminator", {170}, {{"lints", "FINDS"}}},
        {"CTRL-SIBLING-ASYMMETRY", "integer param guarded in sibling only", {}, {{"lints", "FINDS"}}},
        {"API-IGNORED-ERROR", "discarded malloc/fopen/open result", {252, 391}, {{"lints", "FINDS"}}},
        {"API-SCANF-UNCHECKED", "scanf family return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-GETS", "gets() is unbounded", {242, 120}, {{"lints", "FINDS"}}},
        {"API-STRTOK-REENTRANT", "strtok() is not reentrant", {477}, {{"lints", "FINDS"}}},
        {"API-MKSTEMP", "mkstemp template is a string literal", {377}, {{"lints", "FINDS"}}},
        {"API-TMPNAM", "tmpnam/tempnam insecure temp path", {377}, {{"lints", "FINDS"}}},
        {"API-MKTEMP", "mktemp() is an insecure temp-name API", {377}, {{"lints", "FINDS"}}},
        {"API-SIGNAL", "signal() handler install; prefer sigaction", {479}, {{"lints", "FINDS"}}},
        {"FMT-PERCENT-N", "printf format uses %n write-back", {685, 134}, {{"lints", "FINDS"}}},
        {"API-SYSTEM", "system() with non-literal command", {78}, {{"lints", "FINDS"}}},
        {"API-CHROOT", "chroot without chdir into new root", {243}, {{"lints", "FINDS"}}},
        {"INT-ATOI", "atoi result used as index or size unchecked", {190, 128}, {{"lints", "FINDS"}}},
        {"STR-SPRINTF", "sprintf into fixed local buffer", {120}, {{"lints", "FINDS"}}},
        {"RES-FD-LEAK", "descriptor closed on some returns only", {775}, {{"lints", "FINDS"}}},
        {"API-GETENV-NULL", "getenv result used without NULL test", {690, 476}, {{"lints", "FINDS"}}},
        {"API-STRDUP-NULL", "strdup/strndup result used without NULL test", {690}, {{"lints", "FINDS"}}},
        {"MEM-SIZEOF-PTR", "allocation size is sizeof(pointer) not pointee", {131}, {{"lints", "FINDS"}}},
        {"API-POPEN", "popen stream not pclosed on every exit", {775}, {{"lints", "FINDS"}}},
        {"API-UMASK", "umask(0) leaves world-writable default", {732}, {{"lints", "FINDS"}}},
        {"API-FORK", "fork()/vfork() result unused", {362, 273}, {{"lints", "FINDS"}}},
        {"API-EXEC", "exec* with a non-literal path", {78}, {{"lints", "FINDS"}}},
        {"API-MMAP", "mmap() result used without MAP_FAILED test", {252, 119}, {{"lints", "FINDS"}}},
        {"STR-WCSCPY", "unbounded wcscpy/wcscat into local wchar buffer", {120}, {{"lints", "FINDS"}}},
        {"API-GETCWD", "getcwd result used without NULL test", {252, 476}, {{"lints", "FINDS"}}},
        {"API-IOCTL", "ioctl() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-DLOPEN", "dlopen() result used without NULL test", {252}, {{"lints", "FINDS"}}},
        {"API-ACCEPT", "accept()/accept4() result used without < 0 test", {252}, {{"lints", "FINDS"}}},
        {"API-REALPATH", "realpath result used without NULL test", {252, 22}, {{"lints", "FINDS"}}},
        {"API-CHMOD-WORLD", "chmod/fchmod with world-writable mode 0777", {732}, {{"lints", "FINDS"}}},
        {"INT-CLZ-ZERO", "__builtin_clz/ctz on 0 or an unguarded variable", {758}, {{"lints", "FINDS"}}},
        {"MEM-BCOPY", "bcopy with identical source and destination", {628}, {{"lints", "FINDS"}}},
        {"API-SETUID", "setuid/seteuid/setgid to 0 without a return check", {250}, {{"lints", "FINDS"}}},
        {"API-SOCKET", "socket() result used without < 0 test", {252}, {{"lints", "FINDS"}}},
        {"API-BIND", "bind() return discarded", {252}, {{"lints", "FINDS"}}},
        {"STR-SNPRINTF", "snprintf size larger than local destination array", {120}, {{"lints", "FINDS"}}},
        {"API-UNLINK", "unlink/remove return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-MKFIFO", "mkfifo/mknod return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-LISTEN", "listen() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-CONNECT", "connect() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-PIPE", "pipe()/pipe2() result used without a <0 test", {252}, {{"lints", "FINDS"}}},
        {"API-DUP", "dup/dup2/dup3 result used without a <0 test", {252}, {{"lints", "FINDS"}}},
        {"API-FCNTL", "fcntl() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-WAIT", "wait/waitpid/waitid return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-SELECT", "select/poll/epoll_wait return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-SEND", "send/recv/sendto/recvfrom return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-SHUTDOWN", "shutdown() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-KILL", "kill/raise return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-GETADDRINFO", "getaddrinfo result used without a ==0 test", {252}, {{"lints", "FINDS"}}},
        {"API-PTHREAD-JOIN", "pthread_join()/pthread_detach() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-THRD-JOIN", "ISO C11 thrd_join()/thrd_detach() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-SEM-WAIT", "sem_wait()/sem_post() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-OPENAT", "openat() result used without a <0 test", {252}, {{"lints", "FINDS"}}},
        {"API-FLOCK", "flock() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-CHOWN", "chown/fchown/lchown return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-SYMLINK", "symlink()/readlink() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-OPENDIR", "opendir() result used without a NULL test", {252, 476}, {{"lints", "FINDS"}}},
        {"API-SETRLIMIT", "setrlimit()/getrlimit() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-GETSOCKOPT", "getsockopt()/setsockopt() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-STAT", "stat()/lstat()/fstat() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-MKDIR", "mkdir()/rmdir() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-GETPWUID", "getpwuid()/getpwnam() result used without a NULL test", {252, 476}, {{"lints", "FINDS"}}},
        {"API-CLOCK-GETTIME", "clock_gettime()/gettimeofday() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-SHM-OPEN", "shm_open() result used without a <0 test", {252}, {{"lints", "FINDS"}}},
        {"API-POSIX-SPAWN", "posix_spawn()/posix_spawnp() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-GLOB", "glob() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-FSEEK", "fseek()/ftell() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-ACCESS", "access() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-GETOPT", "getopt()/getopt_long() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-UNAME", "uname()/gethostname() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-SENDFILE", "sendfile()/copy_file_range() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-MEMFD", "memfd_create() result used without a <0 test", {252}, {{"lints", "FINDS"}}},
        {"API-PRCTL", "prctl()/ptrace() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-TCGETATTR", "tcgetattr()/tcsetattr() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-SYSCONF", "sysconf()/pathconf() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-GETRUSAGE", "getrusage() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-NFTW", "nftw()/ftw() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-WORDEXP", "wordexp() return discarded (not compared to 0)", {252}, {{"lints", "FINDS"}}},
        {"API-GETLOGIN", "getlogin()/ttyname() result used without a NULL test", {252, 476}, {{"lints", "FINDS"}}},
        {"API-INET-PTON", "inet_pton()/inet_aton() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-MLOCK", "mlock()/munlock() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-SPLICE", "splice() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-INOTIFY", "inotify_init()/inotify_init1() result used without a <0 test", {252}, {{"lints", "FINDS"}}},
        {"API-FSYNC", "fsync()/fdatasync() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-GETRANDOM", "getrandom()/getentropy() return discarded", {252, 330}, {{"lints", "FINDS"}}},
        {"API-GETLINE", "getline()/getdelim() return discarded (not compared to -1)", {252}, {{"lints", "FINDS"}}},
        {"API-ASPRINTF", "asprintf()/vasprintf() return discarded (not compared to 0/-1)", {252}, {{"lints", "FINDS"}}},
        {"API-STRLCPY", "strlcpy()/strlcat() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-ISATTY", "isatty() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-PTSNAME", "ptsname() result used without a NULL test", {252, 476}, {{"lints", "FINDS"}}},
        {"API-MOUNT", "mount()/umount() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-FMEMOPEN", "fmemopen()/open_memstream() result used without a NULL test", {252, 476}, {{"lints", "FINDS"}}},
        {"API-SCANDIR", "scandir() return discarded (not compared to <0)", {252}, {{"lints", "FINDS"}}},
        {"API-SETXATTR", "setxattr()/getxattr()/listxattr() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-SCHED-AFFINITY", "sched_setaffinity()/sched_getaffinity() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-AIO", "aio_read()/aio_write() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-STATX", "statx() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-PIDFD", "pidfd_open() result used without a <0 test", {252}, {{"lints", "FINDS"}}},
        {"API-CAPSET", "capset()/capget() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-FANOTIFY", "fanotify_init() result used without a <0 test", {252}, {{"lints", "FINDS"}}},
        {"API-SECCOMP", "seccomp() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-GETGRNAM", "getgrnam()/getgrgid()/getspnam() result used without a NULL test", {252, 476}, {{"lints", "FINDS"}}},
        {"API-FALLOCATE", "posix_fallocate()/fallocate() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-CLOSE-RANGE", "close_range() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-BPF", "bpf() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-USERFAULTFD", "userfaultfd() result used without a <0 test", {252}, {{"lints", "FINDS"}}},
        {"API-GETPASS", "getpass() result used without a NULL test", {252, 476}, {{"lints", "FINDS"}}},
        {"API-INITGROUPS", "initgroups()/setgroups() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-CLONE", "unshare()/setns()/clone() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-OPENAT2", "openat2() result used without a <0 test", {252}, {{"lints", "FINDS"}}},
        {"API-LANDLOCK", "landlock_create_ruleset() result used without a <0 test", {252}, {{"lints", "FINDS"}}},
        {"API-GETPRIORITY", "getpriority()/setpriority() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-SIGNALFD", "signalfd() result used without a <0 test", {252}, {{"lints", "FINDS"}}},
        {"API-SENDMMSG", "sendmmsg()/recvmmsg() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-PERSONALITY", "personality() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-QUOTACTL", "quotactl() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-NAME-TO-HANDLE", "name_to_handle_at()/open_by_handle_at() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-PROCESS-MADVISE", "process_madvise() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-PIVOT-ROOT", "pivot_root() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-STATFS", "statfs()/fstatfs() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-PRLIMIT", "prlimit()/prlimit64() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-PERF-EVENT", "perf_event_open() result used without a <0 test", {252}, {{"lints", "FINDS"}}},
        {"API-MEMBARRIER", "membarrier() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-PKEY", "pkey_alloc() result used without a <0 test", {252}, {{"lints", "FINDS"}}},
        {"API-SYNCFS", "syncfs() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-PROCESS-VM", "process_vm_readv()/process_vm_writev() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-CLONE3", "clone3() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-FUTEX", "futex() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-KEYCTL", "keyctl() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-KCMP", "kcmp() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-FSOPEN", "fsopen() result used without a <0 test", {252}, {{"lints", "FINDS"}}},
        {"API-MQ-OPEN", "mq_open() result used without a (mqd_t)-1 / <0 test", {252}, {{"lints", "FINDS"}}},
        {"API-SHMGET", "shmget() return discarded or used without a <0 test", {252}, {{"lints", "FINDS"}}},
        {"API-REBOOT", "reboot() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-ADJTIMEX", "adjtimex() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-SETHOSTNAME", "sethostname() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-SWAPON", "swapon()/swapoff() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-ACCT", "acct() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-IOPERM", "ioperm()/iopl() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-MINCORE", "mincore() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-RSEQ", "rseq() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-TIMER-CREATE", "timer_create() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-SEMGET", "semget() return discarded or used without a <0 test", {252}, {{"lints", "FINDS"}}},
        {"API-MSGGET", "msgget() return discarded or used without a <0 test", {252}, {{"lints", "FINDS"}}},
        {"API-KLOGCTL", "klogctl() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-MOUNT-SETATTR", "mount_setattr() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-GETCPU", "getcpu() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-PROCESS-MRELEASE", "process_mrelease() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-MEMFD-SECRET", "memfd_secret() result used without a <0 test", {252}, {{"lints", "FINDS"}}},
        {"API-IOPRIO", "ioprio_set()/ioprio_get() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-INIT-MODULE", "init_module()/finit_module()/delete_module() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-KEXEC", "kexec_load()/kexec_file_load() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-QUOTACTL-FD", "quotactl_fd() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-PKEY-FREE", "pkey_free()/pkey_mprotect() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-TGKILL", "tgkill() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-ADD-KEY", "add_key() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-SEMCTL", "semctl() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-MSGCTL", "msgctl() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-IO-SETUP", "io_setup()/io_destroy()/io_cancel()/io_pgetevents() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-REQUEST-KEY", "request_key() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-TKILL", "tkill() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-TIMER-DELETE", "timer_delete()/timer_gettime()/timer_getoverrun() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-MQ-UNLINK", "mq_unlink()/mq_timedsend()/mq_timedreceive()/mq_notify()/mq_getsetattr() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-SHMAT", "shmat()/shmdt() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-SEMOP", "semop()/semtimedop() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-MSGSND", "msgsnd()/msgrcv() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-SYNC-FILE-RANGE", "sync_file_range() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-MSYNC", "msync()/mremap() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-SOCKETPAIR", "socketpair() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-SYSINFO", "sysinfo() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-CLOCK-SETTIME", "clock_settime()/clock_adjtime()/clock_nanosleep() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-SETTIMEOFDAY", "settimeofday() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-GETTID", "gettid() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-SCHED-SETSCHEDULER", "sched_setscheduler()/sched_getscheduler()/sched_setparam()/sched_getparam() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-SETITIMER", "setitimer()/getitimer() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-NICE", "nice() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-ARCH-PRCTL", "arch_prctl() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-GETDENTS", "getdents()/getdents64() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-UTIMENSAT", "utimensat()/futimens()/utimes() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-LINKAT", "linkat() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-MBIND", "mbind()/set_mempolicy()/get_mempolicy() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-FUTEX-WAITV", "futex_waitv() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-SYSLOG", "syslog() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-SETPGID", "setpgid()/setsid()/getsid() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-SETREUID", "setreuid()/setregid()/setresuid()/setresgid() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-GETGROUPS", "getgroups() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-EPOLL-CREATE", "epoll_create()/epoll_create1() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-TIMERFD-SETTIME", "timerfd_settime()/timerfd_gettime() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-REMAP-FILE-PAGES", "remap_file_pages() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-MOVE-PAGES", "migrate_pages()/move_pages() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-CACHESTAT", "cachestat() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-MAP-SHADOW-STACK", "map_shadow_stack() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-SCHED-YIELD", "sched_yield() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-SETFSUID", "setfsuid()/setfsgid() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-WAIT4", "wait4()/wait3() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-PREADV", "preadv()/pwritev()/preadv2()/pwritev2() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-SENDMSG", "sendmsg()/recvmsg() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-GETSOCKNAME", "getsockname()/getpeername() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-EPOLL-PWAIT", "epoll_pwait()/epoll_pwait2() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-INOTIFY-RM-WATCH", "inotify_rm_watch() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-EVENTFD-READ", "eventfd_read()/eventfd_write() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-SCHED-SETATTR", "sched_setattr()/sched_getattr() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-RENAMEAT2", "renameat2() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-EXECVEAT", "execveat() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-MLOCK2", "mlock2() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-FACCESSAT2", "faccessat2() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-POSIX-FADVISE", "posix_fadvise()/posix_fadvise64() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-READAHEAD", "readahead() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-SIGACTION", "sigaction() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-SIGPROCMASK", "sigprocmask()/sigsuspend() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-SEM-OPEN", "sem_open()/sem_close()/sem_unlink() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-RWLOCK", "pthread_rwlock_rdlock()/wrlock()/unlock() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-PTHREAD-COND", "pthread_cond_wait()/timedwait()/signal() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-SIGALTSTACK", "sigaltstack() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-RENAMEAT", "renameat() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-FACCESSAT", "faccessat() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-FCHMODAT", "fchmodat() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-PTHREAD-BARRIER", "pthread_barrier_wait()/init()/destroy() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-SYMLINKAT", "symlinkat() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-UNLINKAT", "unlinkat() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-MKDIRAT", "mkdirat() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-MKNODAT", "mknodat() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-READLINKAT", "readlinkat() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-FSTATAT", "fstatat() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-PTHREAD-SPIN", "pthread_spin_lock()/unlock()/trylock()/init()/destroy() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-PTHREAD-KEY", "pthread_key_create()/key_delete()/setspecific()/getspecific() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-PTHREAD-CANCEL", "pthread_cancel() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-PTHREAD-KILL", "pthread_kill() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-PTHREAD-SIGMASK", "pthread_sigmask() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-PTHREAD-ATFORK", "pthread_atfork() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-PLEDGE", "pledge() return discarded", {252, 250, 273}, {{"lints", "FINDS"}}},
        {"API-UNVEIL", "unveil() return discarded", {252, 250, 273}, {{"lints", "FINDS"}}},
        {"API-SYSCTL", "sysctl()/sysctlbyname() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-KQUEUE", "kqueue() result used without a <0 test or discarded", {252}, {{"lints", "FINDS"}}},
        {"API-KEVENT", "kevent() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-PAUSE", "pause() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-PPOLL", "ppoll() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-SIGWAIT", "sigwait()/sigwaitinfo()/sigtimedwait()/sigpending() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-SIGQUEUE", "sigqueue() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-UCONTEXT", "getcontext()/setcontext()/swapcontext()/makecontext() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-SEM-TIMEDWAIT", "sem_timedwait() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-PTHREAD-ATTR", "pthread_attr_init()/destroy()/setstack*/setdetachstate() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-CAP-ENTER", "cap_enter() return discarded", {252, 250, 273}, {{"lints", "FINDS"}}},
        {"API-CAP-RIGHTS", "cap_rights_limit()/cap_rights_get() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-PDFORK", "pdfork() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-PROCCTL", "procctl() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-CLOSEFROM", "closefrom() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-ISSETUGID", "issetugid() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-ARC4RANDOM", "arc4random()/arc4random_buf()/arc4random_uniform() return discarded", {252, 330}, {{"lints", "FINDS"}}},
        {"API-CHFLAGS", "chflags()/fchflags()/lchflags() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-GETFSSTAT", "getfsstat() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-PTHREAD-YIELD", "pthread_yield() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-SEM-TRYWAIT", "sem_trywait()/sem_getvalue() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-ADJTIME", "adjtime()/ntp_adjtime() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-REVOKE", "revoke() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-KTRACE", "ktrace() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-RFORK", "rfork() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-JAIL", "jail()/jail_attach()/jail_get()/jail_set()/jail_remove() return discarded", {252, 250}, {{"lints", "FINDS"}}},
        {"API-SETLOGIN", "setlogin() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-GETRESUID", "getresuid()/getresgid() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-GETPEEREID", "getpeereid() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-STRTONUM", "strtonum() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-REALLOCARRAY", "reallocarray() return discarded or used without a NULL check", {252, 190, 680}, {{"lints", "FINDS"}}},
        {"API-TIMINGSAFE", "timingsafe_bcmp()/timingsafe_memcmp() return discarded", {252, 208}, {{"lints", "FINDS"}}},
        {"API-GETPROGNAME", "getprogname()/setprogname() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-DAEMON", "daemon()/setproctitle() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-CAP-FCNTLS", "cap_fcntls_limit()/cap_ioctls_limit() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-PDGETPID", "pdgetpid()/pdwait4() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-KLDLOAD", "kldload()/kldunload()/kldfind()/kldsym()/kldstat() return discarded", {252, 114}, {{"lints", "FINDS"}}},
        {"API-EXTATTR", "extattr_set_file()/extattr_get_file()/extattr_delete_file() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-MAC", "mac_set_proc()/mac_get_proc()/mac_set_fd() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-AUDIT", "auditon()/getaudit()/setaudit()/auditctl() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-KVM", "kvm_open()/kvm_openfiles()/kvm_getprocs()/kvm_close() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-REALLOCF", "reallocf() return discarded or used without a NULL check", {252, 401, 680}, {{"lints", "FINDS"}}},
        {"API-UUIDGEN", "uuidgen() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-SETFIB", "setfib() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-NTP-GETTIME", "ntp_gettime() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-CRYPT-NEWHASH", "crypt_newhash()/crypt_checkpass() return discarded", {252, 916}, {{"lints", "FINDS"}}},
        {"API-WAIT6", "wait6() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-CPUSET", "cpuset_setaffinity()/cpuset_getaffinity() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-RTPRIO", "rtprio()/rtprio_thread() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-KENV", "kenv() return discarded", {252, 526}, {{"lints", "FINDS"}}},
        {"API-GETFH", "getfh()/fhopen()/fhstat()/fhstatfs() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-GETMNTINFO", "getmntinfo() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-NMOUNT", "nmount() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-STRMODE", "strmode() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-GETOSRELDATE", "getosreldate() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-CAP-SANDBOXED", "cap_sandboxed() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-GETGROUPLIST", "getgrouplist() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-EACCESS", "eaccess() return discarded", {252, 284}, {{"lints", "FINDS"}}},
        {"API-LOGIN-GETCLASS", "login_getclass()/setusercontext() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-FFLAGS", "fflagstostr()/strtofflags() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-GETDIRENTRIES", "getdirentries() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-KINFO", "kinfo_getproc()/kinfo_getfile() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-UMTX", "_umtx_op() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-THR", "thr_new()/thr_kill()/thr_kill2() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-MODFIND", "modfind()/modstat()/modnext() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-LPATHCONF", "lpathconf() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-LOGINCLASS", "getloginclass()/setloginclass() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-GETFSENT", "getfsent()/setfsent()/endfsent() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-MINHERIT", "minherit() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-CAP-GETMODE", "cap_getmode() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-NFSSVC", "nfssvc() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-SYSARCH", "sysarch() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-GETPAGESIZES", "getpagesizes() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-SBRK", "sbrk()/brk() return discarded", {252, 770}, {{"lints", "FINDS"}}},
        {"API-KSEM", "ksem_open()/ksem_close()/ksem_unlink() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-CAP-GETRIGHTS", "cap_getrights() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-DEVNAME", "devname()/devname_r() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-GETBOOTFILE", "getbootfile() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-KLDFIRSTMOD", "kldfirstmod()/kldnextmod() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-FHLINK", "fhlink()/fhlinkat()/fhreadlink() return discarded", {252}, {{"lints", "FINDS"}}},
        {"API-VALLOC", "valloc() return discarded or used without a NULL check", {252, 590}, {{"lints", "FINDS"}}},
        {"API-GETDOMAINNAME", "getdomainname() return discarded", {252}, {{"lints", "FINDS"}}},
        {"STR-STRNCPY-NUL", "strncpy into local array without an explicit NUL store", {170}, {{"lints", "FINDS"}}},
        {"MEM-VLA-SIZE", "variable-length local array", {758}, {{"lints", "FINDS"}}},
        {"MEM-ALLOCA", "alloca size is not a constant", {770, 1325}, {{"lints", "FINDS"}}},
        {"MEM-FLEX-ARRAY", "flexible-array struct allocated at header size only", {131, 119}, {{"lints", "FINDS"}}},
        {"MEM-LEAK", "heap allocation freed on some returns only", {401}, {{"lints", "FINDS"}}},
        {"STR-NULL-ARG", "string API called on unchecked pointer parameter", {476}, {{"lints", "FINDS"}}},
        {"CXX-USE-AFTER-MOVE", "value used after std::move", {672}, {{"lints", "FINDS"}}},
        {"CXX-DANGLING-REF", "view or span borrows local storage", {416}, {{"lints", "FINDS"}}},
        {"CXX-ITERATOR-INVALID", "iterator used after container mutation", {119}, {{"lints", "FINDS"}}},
        {"CXX-SELF-ASSIGN", "assignment without self-test", {762}, {{"lints", "FINDS"}}},
        {"CXX-DELETE-THIS", "delete this while the member function still runs", {416}, {{"lints", "FINDS"}}},
        {"CXX-CATCH-BY-VALUE", "exception caught by value (slicing)", {704}, {{"lints", "FINDS"}}},
        {"CXX-THROW-NOEXCEPT", "throw in noexcept or throw() function", {248}, {{"lints", "FINDS"}}},
        {"CXX-MISSING-VIRTUAL-DTOR", "delete base pointer to class without virtual destructor", {762}, {{"lints", "FINDS"}}},
        {"CXX-LAMBDA-DANGLE", "returned lambda captures local by reference", {416, 562}, {{"lints", "FINDS"}}},
        {"CXX-UNIQUE-RESET", "raw pointer from unique_ptr::get used after reset", {416}, {{"lints", "FINDS"}}},
        {"CXX-CONST-CAST", "const_cast write through formerly const object", {704, 758}, {{"lints", "FINDS"}}},
        {"CXX-DYNAMIC-CAST-NULL", "dynamic_cast result used without null test", {476}, {{"lints", "FINDS"}}},
        {"CXX-REINTERPRET", "reinterpret_cast type-puns object pointers", {704}, {{"lints", "FINDS"}}},
        {"CXX-THROW-COPY", "throw caught exception object (slicing)", {703}, {{"lints", "FINDS"}}},
        {"CXX-BIT-CAST", "bit_cast between object pointer and integer or unrelated object types", {704}, {{"lints", "FINDS"}}},
        {"CXX-PLACEMENT-NEW", "placement new into a typed object pointer", {704, 762}, {{"lints", "FINDS"}}},
        {"CXX-STD-THREAD", "std::thread not joined or detached", {833}, {{"lints", "FINDS"}}},
        {"CXX-OPTIONAL-NULL", "dereference of std::optional without has_value", {476}, {{"lints", "FINDS"}}},
        {"CXX-VARIANT-GET", "std::get without holds_alternative", {704}, {{"lints", "FINDS"}}},
        {"CXX-SPAN-DANGLE", "std::span constructed from a local then returned", {416}, {{"lints", "FINDS"}}},
        {"CXX-VECTOR-INDEX", "vector/string subscript without a size guard", {125}, {{"lints", "FINDS"}}},
        {"CXX-CATCH-ALL", "empty catch (...) swallows exceptions", {703}, {{"lints", "FINDS"}}},
        {"CXX-THROW-NEW", "throw new allocates the exception with new", {248}, {{"lints", "FINDS"}}},
        {"CXX-UNINIT-MEMBER", "constructor leaves a scalar member uninitialised", {457}, {{"lints", "FINDS"}}},
        {"CXX-COPY-ASSIGN-PTR", "operator= shallow-copies a raw pointer member", {762}, {{"lints", "FINDS"}}},
        {"CXX-VOLATILE-CAST", "C-style cast away from volatile then write", {758}, {{"lints", "FINDS"}}},
        {"CXX-SHARED-PTR-GET", "raw pointer from shared_ptr::get used after reset", {416}, {{"lints", "FINDS"}}},
        {"CXX-AUTO-PTR", "use of deprecated std::auto_ptr", {676}, {{"lints", "FINDS"}}},
        {"CXX-STRING-DATA", "pointer from string c_str/data used after mutation", {416}, {{"lints", "FINDS"}}},
        {"CXX-ENABLE-SHARED", "shared_from_this without enable_shared_from_this", {664}, {{"lints", "FINDS"}}},
        {"CXX-FORWARDING-REF", "T&& pushed into a container without std::forward", {704}, {{"lints", "FINDS"}}},
        {"CXX-EXPLICIT-CTOR", "operator bool conversion without explicit", {704}, {{"lints", "FINDS"}}},
        {"CXX-MOVE-CONST", "std::move of a const object", {704}, {{"lints", "FINDS"}}},
        {"CXX-BIND-TMP", "reference bound to a temporary then returned", {562}, {{"lints", "FINDS"}}},
        {"CXX-EXPECTED-NULL", "std::expected value accessed without has_value", {476}, {{"lints", "FINDS"}}},
        {"CXX-STD-FORMAT", "std::format/print with a non-literal format string", {134}, {{"lints", "FINDS"}}},
        {"CXX-THIS-CAPTURE", "returned lambda captures this by [=] or [this]", {416, 562}, {{"lints", "FINDS"}}},
        {"CXX-SPACESHIP-DEFAULT", "defaulted operator<=> with a pointer member", {704}, {{"lints", "FINDS"}}},
        {"CXX-STD-ASYNC", "std::async result discarded", {252}, {{"lints", "FINDS"}}},
        {"CXX-FUTURE-GET", "std::future::get without a prior assignment", {394}, {{"lints", "FINDS"}}},
        {"CXX-STD-FUNCTION-NULL", "std::function invoked without a truth test", {476}, {{"lints", "FINDS"}}},
        {"CXX-NODISCARD", "[[nodiscard]] result discarded", {252}, {{"lints", "FINDS"}}},
        {"CXX-STD-JTHREAD", "std::jthread constructed without request_stop", {833}, {{"lints", "FINDS"}}},
        {"CXX-MDSPAN-DANGLE", "std::mdspan constructed from a local then returned", {416}, {{"lints", "FINDS"}}},
        {"CXX-ATOMIC-REF", "std::atomic_ref constructed from a local then returned", {416}, {{"lints", "FINDS"}}},
        {"CXX-CONDITION-WAIT", "condition_variable wait without a predicate", {662}, {{"lints", "FINDS"}}},
        {"CXX-STD-BIND", "use of std::bind; prefer a lambda", {676}, {{"lints", "FINDS"}}},
        {"CXX-ASSUME", "[[assume(false)]] / [[assume(0)]] in a function that still returns", {758}, {{"lints", "FINDS"}}},
        {"CXX-GENERATOR", "std::generator yields a pointer or reference to a local", {416}, {{"lints", "FINDS"}}},
        {"CXX-SHARED-MUTEX", "std::shared_mutex lock() without unlock or lock_guard", {667}, {{"lints", "FINDS"}}},
        {"CXX-ANY-CAST", "std::any_cast by value without type check or pointer form", {704}, {{"lints", "FINDS"}}},
        {"CXX-FILESYSTEM", "std::filesystem::remove then use of the same path", {367}, {{"lints", "FINDS"}}},
        {"CXX-REGEX", "std::regex constructed from a non-literal pattern", {185}, {{"lints", "FINDS"}}},
        {"CXX-LATCH", "std::latch wait without count_down in the same function", {667}, {{"lints", "FINDS"}}},
        {"CXX-FROM-CHARS", "std::from_chars result used without checking ec", {252}, {{"lints", "FINDS"}}},
        {"CXX-INIT-LIST-DANGLE", "pointer from a temporary initializer_list used after the full-expression", {562}, {{"lints", "FINDS"}}},
        {"CXX-STOP-TOKEN", "infinite loop with stop_token and no stop_requested", {833}, {{"lints", "FINDS"}}},
        {"CXX-FLAT-MAP", "flat_map at() without contains/count/find", {125}, {{"lints", "FINDS"}}},
        {"CXX-SEMAPHORE", "counting_semaphore acquire without release in the same function", {667}, {{"lints", "FINDS"}}},
        {"CXX-STACKTRACE", "stacktrace::current() [0]/at(0) without empty/size check", {125}, {{"lints", "FINDS"}}},
        {"CXX-UNIQUE-RELEASE", "unique_ptr get used after release", {416}, {{"lints", "FINDS"}}},
        {"CXX-PACK-PRAGMA", "address of a non-char member of a #pragma pack(1) struct", {188}, {{"lints", "FINDS"}}},
        {"CXX-FUNCTION-REF", "function_ref bound to a temporary lambda or call", {416, 562}, {{"lints", "FINDS"}}},
        {"CXX-MOVE-ONLY-FUNCTION", "move_only_function invoked without a truth test", {476}, {{"lints", "FINDS"}}},
        {"CXX-RANGES-DANGLE", "ranges view pipeline over a temporary range", {416}, {{"lints", "FINDS"}}},
        {"CXX-CHRONO-SEED", "PRNG seeded from chrono clock::now()", {330}, {{"lints", "FINDS"}}},
        {"CXX-INPLACE-VECTOR", "inplace_vector push_back without size/capacity guard", {787}, {{"lints", "FINDS"}}},
        {"CXX-FLAT-SET", "flat_set find dereference without end() check", {476}, {{"lints", "FINDS"}}},
        {"CXX-COPYABLE-FUNCTION", "copyable_function invoked without a truth test", {476}, {{"lints", "FINDS"}}},
        {"CXX-HIVE", "hive iterator used after insert/emplace/erase", {119}, {{"lints", "FINDS"}}},
        {"CXX-BITSET-INDEX", "bitset test/subscript without a size guard", {125}, {{"lints", "FINDS"}}},
        {"CXX-SSTREAM-VIEW", "string_view or c_str of stringstream::str() temporary", {416}, {{"lints", "FINDS"}}},
        {"CXX-OPTIONAL-VALUE", "optional.value() without has_value", {476}, {{"lints", "FINDS"}}},
        {"CXX-INDIRECT", "dereference of default-constructed empty std::indirect", {476}, {{"lints", "FINDS"}}},
        {"CXX-TO-CHARS", "std::to_chars result used without checking ec/ptr", {252}, {{"lints", "FINDS"}}},
        {"CXX-HAZARD-POINTER", "hazard_pointer constructed but atomic load used without protect", {416}, {{"lints", "FINDS"}}},
        {"CXX-TEXT-ENCODING", "std::text_encoding constructed from a non-literal name", {176}, {{"lints", "FINDS"}}},
        {"CXX-EXPECTED-ERROR", "std::expected error() without a prior !e / !has_value check", {390}, {{"lints", "FINDS"}}},
        {"CXX-VARIANT-VALUELSS", "std::get after emplace without valueless_by_exception check", {704}, {{"lints", "FINDS"}}},
        {"CXX-SIMD-INDEX", "std::simd subscript without a size guard", {125}, {{"lints", "FINDS"}}},
        {"CXX-RCU", "rcu_obj update or retire without rcu_synchronize", {416}, {{"lints", "FINDS"}}},
        {"CXX-LINALG", "linalg matrix index without an extents guard", {125}, {{"lints", "FINDS"}}},
        {"CXX-SYNC-WAIT", "std::execution::sync_wait result discarded", {252}, {{"lints", "FINDS"}}},
        {"CXX-EMBED", "#embed used as a pointer without a size, or non-literal embed path", {125}, {{"lints", "FINDS"}}},
        {"CXX-CONTRACTS", "contract_assert(false)/pre(false) in a function that still returns", {758}, {{"lints", "FINDS"}}},
        {"CXX-REFLECTION", "std::meta define_aggregate/define_class without a named namespace", {284}, {{"lints", "FINDS"}}},
        {"CXX-OUT-PTR", "unique_ptr/shared_ptr used after out_ptr without a null check", {476}, {{"lints", "FINDS"}}},
        {"CXX-FLAT-MULTIMAP", "flat_multimap find dereference without end() check", {476}, {{"lints", "FINDS"}}},
        {"CXX-SPANSTREAM", "spanstream span() data or string_view outlives the stream", {416}, {{"lints", "FINDS"}}},
        {"CXX-BARRIER", "std::barrier arrive without wait in the same function", {667}, {{"lints", "FINDS"}}},
        {"CXX-TASK", "std::task started without sync_wait or co_await", {252}, {{"lints", "FINDS"}}},
        {"CXX-GENERATOR-DISCARD", "std::generator constructed and not iterated", {252}, {{"lints", "FINDS"}}},
        {"CXX-OSYNCSTREAM", "osyncstream destroyed without emit()", {662}, {{"lints", "FINDS"}}},
        {"CXX-PACKAGED-TASK", "packaged_task invoked without a truth test", {476}, {{"lints", "FINDS"}}},
        {"CXX-FLAT-MULTISET", "flat_multiset find dereference without end() check", {476}, {{"lints", "FINDS"}}},
        {"CXX-SYNCBUF", "syncbuf destroyed without emit()", {662}, {{"lints", "FINDS"}}},
        {"CXX-COUNTED-ITERATOR", "counted_iterator constructed without a count vs remaining-size guard", {125}, {{"lints", "FINDS"}}},
        {"CXX-PROMISE", "promise get_future used without set_value/set_exception", {394}, {{"lints", "FINDS"}}},
        {"CXX-WEAK-PTR", "weak_ptr.lock() used without expired() or a truth test", {416}, {{"lints", "FINDS"}}},
        {"CXX-EXCEPTION-PTR", "exception_ptr rethrown without a nullptr test", {476}, {{"lints", "FINDS"}}},
        {"CXX-CORO-HANDLE", "coroutine_handle.resume() without done()", {762}, {{"lints", "FINDS"}}},
        {"CXX-VALARRAY", "valarray operator[] without a size() guard", {125}, {{"lints", "FINDS"}}},
        {"CXX-TO-UNDERLYING", "to_underlying used without an enum-range guard", {704}, {{"lints", "FINDS"}}},
        {"CXX-UNEXPECTED", "std::unexpected< constructed and discarded (not used as expected error path)", {252}, {{"lints", "FINDS"}}},
        {"CXX-TUPLE-GET", "std::get on tuple without a tuple_size/index-in-range guard", {125}, {{"lints", "FINDS"}}},
        {"CXX-DEQUE-INDEX", "deque operator[] without size()", {125}, {{"lints", "FINDS"}}},
        {"CXX-FORWARD-LIST", "forward_list.front() without empty()", {125}, {{"lints", "FINDS"}}},
        {"CXX-LIST-FRONT", "std::list.front()/.back() without empty()", {125}, {{"lints", "FINDS"}}},
        {"CXX-MAP-AT", "std::map .at( without count()/find()/contains()", {125}, {{"lints", "FINDS"}}},
        {"CXX-UNORDERED-AT", "unordered_map .at( without count()/find()/contains()", {125}, {{"lints", "FINDS"}}},
        {"CXX-SET-FIND", "std::set find dereference without end()", {476}, {{"lints", "FINDS"}}},
        {"CXX-QUEUE-FRONT", "std::queue .front()/.pop() without empty()", {125}, {{"lints", "FINDS"}}},
        {"CXX-STACK-TOP", "std::stack .top()/.pop() without empty()", {125}, {{"lints", "FINDS"}}},
        {"CXX-PRIORITY-QUEUE", "std::priority_queue .top()/.pop() without empty()", {125}, {{"lints", "FINDS"}}},
        {"CXX-ARRAY-INDEX", "std::array operator[] without size()/N guard", {125}, {{"lints", "FINDS"}}},
        {"CXX-UNORDERED-SET", "unordered_set find dereference without end()", {476}, {{"lints", "FINDS"}}},
        {"CXX-WSTRING-VIEW", "wstring_view / wstring borrows local storage", {416}, {{"lints", "FINDS"}}},
        {"CXX-MULTIMAP-FIND", "std::multimap find dereference without end()", {476}, {{"lints", "FINDS"}}},
        {"CXX-MULTISET-FIND", "std::multiset find dereference without end()", {476}, {{"lints", "FINDS"}}},
        {"CXX-BINARY-SEMAPHORE", "binary_semaphore(0) acquire without try_acquire or release", {667}, {{"lints", "FINDS"}}},
        {"CXX-ERROR-CODE", "std::error_code used without if(ec) or .value() check", {252}, {{"lints", "FINDS"}}},
        {"CXX-BYTESWAP", "byteswap result used as array index without a range check", {125}, {{"lints", "FINDS"}}},
        {"CXX-PMR", "std::pmr container operator[] without size() guard", {125}, {{"lints", "FINDS"}}},
        {"CXX-U8STRING-VIEW", "u8string_view / u8string borrows local storage", {416}, {{"lints", "FINDS"}}},
        {"CXX-UNORDERED-MULTIMAP", "unordered_multimap find dereference without end()", {476}, {{"lints", "FINDS"}}},
        {"CXX-UNORDERED-MULTISET", "unordered_multiset find dereference without end()", {476}, {{"lints", "FINDS"}}},
        {"CXX-SHARED-LOCK", "std::shared_lock used without owns_lock() check", {667}, {{"lints", "FINDS"}}},
        {"CXX-ATOMIC-FLAG", "atomic_flag.test_and_set without a prior clear()", {667}, {{"lints", "FINDS"}}},
        {"CXX-CONDVAR-ANY", "condition_variable_any.wait without a lock / predicate", {662}, {{"lints", "FINDS"}}},
        {"CXX-RECURSIVE-MUTEX", "recursive_mutex.lock() without unlock or lock_guard", {667}, {{"lints", "FINDS"}}},
        {"CXX-TIMED-MUTEX", "timed_mutex try_lock/lock result discarded or lock without unlock", {667}, {{"lints", "FINDS"}}},
        {"CXX-FSTREAM", "ifstream/ofstream used without is_open() or a truth test", {252}, {{"lints", "FINDS"}}},
        {"CXX-THIS-THREAD", "this_thread::sleep_for as the only sync around a shared store", {362, 667}, {{"lints", "FINDS"}}},
        {"CXX-CALL-ONCE", "std::call_once without an once_flag object in scope", {662}, {{"lints", "FINDS"}}},
        {"CXX-SHARED-TIMED-MUTEX", "shared_timed_mutex.lock/lock_shared without unlock", {667}, {{"lints", "FINDS"}}},
        {"CXX-RECURSIVE-TIMED-MUTEX", "recursive_timed_mutex.lock() without unlock", {667}, {{"lints", "FINDS"}}},
        {"CXX-SYSTEM-ERROR", "std::system_error used without a .code() check", {252}, {{"lints", "FINDS"}}},
        {"CXX-CHRONO-TZDB", "chrono current_zone/tzdb used without a null/locate check", {252, 476}, {{"lints", "FINDS"}}},
        {"CXX-RANGES-ZIP", "views::zip / zip_view indexed or iterated without a size guard", {125}, {{"lints", "FINDS"}}},
        {"CXX-FORMAT-TO", "format_to into a raw char buffer without size / format_to_n", {120}, {{"lints", "FINDS"}}},
        {"CXX-ERROR-CATEGORY", "error_category used without generic/system compare or .message()", {252}, {{"lints", "FINDS"}}},
        {"CXX-NESTED-EXCEPTION", "throw_with_nested / nested_exception without a try/catch", {705}, {{"lints", "FINDS"}}},
        {"CXX-ATOMIC-FENCE", "atomic_thread_fence without memory_order or as only sync around a store", {362}, {{"lints", "FINDS"}}},
        {"CXX-NOTIFY-THREAD-EXIT", "notify_all_at_thread_exit without a waiting condition_variable", {662}, {{"lints", "FINDS"}}},
        {"CXX-WSTRING-CONVERT", "wstring_convert without .converted() or dangling local converter", {416, 252}, {{"lints", "FINDS"}}},
        {"CXX-INVOKE", "std::invoke on a nullable callable without a truth test", {476}, {{"lints", "FINDS"}}},
        {"CXX-APPLY", "std::apply on a tuple without a size/tuple_size guard, or apply of a nullable callable", {476}, {{"lints", "FINDS"}}},
        {"CXX-REFERENCE-WRAPPER", "std::ref/cref/reference_wrapper wrapping a local that is returned or escaped", {416}, {{"lints", "FINDS"}}},
        {"CXX-ENDIAN", "std::endian used as an array index or unchecked integer without a range check", {125}, {{"lints", "FINDS"}}},
        {"CXX-BIT-CEIL", "bit_ceil/bit_floor/has_single_bit/popcount used as an index without a range check, or bit_ceil(0)", {125}, {{"lints", "FINDS"}}},
        {"CXX-UNCAUGHT-EXCEPTIONS", "std::uncaught_exceptions() used as a destructor-safety check without comparing to a saved count", {705}, {{"lints", "FINDS"}}},
        {"CXX-RANGES-JOIN", "views::join / join_view indexed or iterated without a size guard", {125}, {{"lints", "FINDS"}}},
        {"CXX-QUICK-EXIT", "std::quick_exit / at_quick_exit without a prior at_quick_exit handler, or quick_exit from a destructor", {670}, {{"lints", "FINDS"}}},
        {"CXX-TO-ARRAY", "std::to_array of a local C array then the source is mutated/destroyed while the std::array is used, or to_array result indexed without size", {125, 416}, {{"lints", "FINDS"}}},
        {"CXX-ZONED-TIME", "std::chrono::zoned_time constructed without a zone / locate_zone null check", {476}, {{"lints", "FINDS"}}},
        {"CXX-KILL-DEPENDENCY", "std::kill_dependency used as the only sync around a shared store, or result used as an index without a range check", {362, 125}, {{"lints", "FINDS"}}},
        {"CXX-ROTL", "std::rotl/std::rotr result used as an array index without a range check", {125}, {{"lints", "FINDS"}}},
        {"CXX-CURRENT-EXCEPTION", "std::current_exception() used without a nullptr test before rethrow_exception", {476}, {{"lints", "FINDS"}}},
        {"CXX-BIT-WIDTH", "std::bit_width result used as an array index without a range check", {125}, {{"lints", "FINDS"}}},
        {"CXX-LERP", "std::lerp result used as an array index without a range check, or lerp with no finite bounds", {125}, {{"lints", "FINDS"}}},
        {"CXX-MIDPOINT", "std::midpoint result used as an array index without a range check", {125}, {{"lints", "FINDS"}}},
        {"CXX-CMP-LESS", "std::cmp_less/in_range result used as an array index, or in_range ignored before a subscript", {125}, {{"lints", "FINDS"}}},
        {"CXX-COUNTL-ZERO", "std::countl_zero/countr_zero/countl_one/countr_one result used as an array index without a range check", {125}, {{"lints", "FINDS"}}},
        {"CXX-UNREACHABLE", "std::unreachable() used as a recoverable path or in a function that also returns", {670}, {{"lints", "FINDS"}}},
        {"CXX-GCD", "std::gcd result used as an array index without a range check", {125}, {{"lints", "FINDS"}}},
        {"CXX-LCM", "std::lcm result used as an array index without a range check", {125}, {{"lints", "FINDS"}}},
        {"CXX-CLAMP", "std::clamp result used as an array index without a range check", {125}, {{"lints", "FINDS"}}},
        {"CXX-EXCHANGE", "std::exchange used then the old value is used after the exchange, or exchange result used as an unguarded index", {672, 125}, {{"lints", "FINDS"}}},
        {"CXX-TO-ADDRESS", "std::to_address on a local unique_ptr/raw pointer then the source is reset/destroyed while the raw pointer is used, or to_address result indexed without a bound", {416, 125}, {{"lints", "FINDS"}}},
        {"CXX-IS-CONSTANT-EVALUATED", "std::is_constant_evaluated() used to pick an unchecked runtime index path", {125}, {{"lints", "FINDS"}}},
        {"CXX-ADDRESSOF", "std::addressof result used as an array index or stored then the object dies", {125, 416}, {{"lints", "FINDS"}}},
        {"CXX-ASSUME-ALIGNED", "std::assume_aligned result indexed without a bound", {125}, {{"lints", "FINDS"}}},
        {"CXX-AS-CONST", "std::as_const used to then const_cast away constness and write, or as_const view of a local then the local dies", {119, 416}, {{"lints", "FINDS"}}},
        {"CXX-EXCLUSIVE-SCAN", "std::exclusive_scan output buffer indexed/used without a size guard, or dest overlaps source", {125}, {{"lints", "FINDS"}}},
        {"CXX-MAKE-EXCEPTION-PTR", "std::make_exception_ptr / the resulting exception_ptr rethrown without a nullptr test", {476}, {{"lints", "FINDS"}}},
        {"CXX-SET-TERMINATE", "std::set_terminate / get_terminate used without storing the previous handler, or terminate handler itself throws", {670}, {{"lints", "FINDS"}}},
        {"CXX-INCLUSIVE-SCAN", "std::inclusive_scan output buffer indexed/used without a size guard, or dest overlaps source", {125}, {{"lints", "FINDS"}}},
        {"CXX-TRANSFORM-REDUCE", "std::transform_reduce result used as an array index without a range check", {125}, {{"lints", "FINDS"}}},
        {"CXX-REDUCE", "std::reduce result used as an array index without a range check", {125}, {{"lints", "FINDS"}}},
        {"CXX-UNINITIALIZED-COPY", "std::uninitialized_copy/uninitialized_move into a buffer without constructing/lifetime, or dest indexed OOB", {125, 824}, {{"lints", "FINDS"}}},
        {"CXX-CONSTRUCT-AT", "std::construct_at/destroy_at on storage then the pointer is used after destroy, or construct_at result indexed OOB", {416, 125}, {{"lints", "FINDS"}}},
        {"CXX-FORWARD-LIKE", "std::forward_like used then the source is moved-from and used", {672}, {{"lints", "FINDS"}}},
        {"CXX-UNINITIALIZED-FILL", "std::uninitialized_fill/uninitialized_default_construct dest indexed OOB", {125}, {{"lints", "FINDS"}}},
        {"CXX-DESTROY-N", "std::destroy_n then the range is used, or count is unchecked", {416}, {{"lints", "FINDS"}}},
        {"CXX-ADD-SAT", "std::add_sat/sub_sat/mul_sat/div_sat/saturate_cast result used as an array index without a range check", {125}, {{"lints", "FINDS"}}},
        {"CXX-TRANSFORM-SCAN", "std::transform_inclusive_scan/transform_exclusive_scan output indexed without a size guard", {125}, {{"lints", "FINDS"}}},
        {"CXX-TYPE-IDENTITY", "std::type_identity used to recast a pointer then indexed OOB", {125}, {{"lints", "FINDS"}}},
        {"CXX-NONTYPE", "std::nontype used as an unguarded index or to bypass a bound", {125}, {{"lints", "FINDS"}}},
        {"CXX-LAYOUT-COMPATIBLE", "std::is_layout_compatible used to recast then indexed OOB", {125}, {{"lints", "FINDS"}}},
        {"CXX-PTR-INTERCONVERTIBLE", "is_pointer_interconvertible_with_class / is_pointer_interconvertible_base_of used to recast then indexed OOB", {125}, {{"lints", "FINDS"}}},
        {"CXX-UNINITIALIZED-VALUE", "std::uninitialized_value_construct dest indexed OOB", {125}, {{"lints", "FINDS"}}},
        {"CXX-CONST-ITERATOR", "std::basic_const_iterator used then written through or indexed OOB", {125, 664}, {{"lints", "FINDS"}}},
        {"CXX-CORRESPONDING-MEMBER", "std::is_corresponding_member used to recast then indexed OOB", {125}, {{"lints", "FINDS"}}},
        {"CXX-RANGES-TO", "std::ranges::to into a container then indexed without a size guard", {125}, {{"lints", "FINDS"}}},
        {"CXX-ENUMERATE", "std::views::enumerate / enumerate_view indexed without a size guard", {125}, {{"lints", "FINDS"}}},
        {"CXX-CARTESIAN-PRODUCT", "std::views::cartesian_product indexed without a size guard", {125}, {{"lints", "FINDS"}}},
        {"CXX-CHUNK", "std::views::chunk / chunk_by / chunk_view indexed without a size guard", {125}, {{"lints", "FINDS"}}},
        {"CXX-SLIDE", "std::views::slide / slide_view indexed without a size guard", {125}, {{"lints", "FINDS"}}},
        {"CXX-ADJACENT", "std::views::adjacent / adjacent_transform / adjacent_view indexed without a size guard", {125}, {{"lints", "FINDS"}}},
        {"CXX-JOIN-WITH", "std::views::join_with / join_with_view indexed without a size guard", {125}, {{"lints", "FINDS"}}},
        {"CXX-ZIP-TRANSFORM", "std::views::zip_transform / zip_transform_view indexed without a size guard", {125}, {{"lints", "FINDS"}}},
        {"CXX-AS-RVALUE", "std::views::as_rvalue / as_rvalue_view indexed OOB or used after the source dies", {125, 664}, {{"lints", "FINDS"}}},
        {"CXX-FROM-RANGE", "std::from_range used to build a container then indexed without a size guard", {125}, {{"lints", "FINDS"}}},
        {"CXX-SCOPED-ENUM", "std::is_scoped_enum used to recast then indexed OOB", {125}, {{"lints", "FINDS"}}},
        {"CXX-STRIDE", "std::views::stride / stride_view indexed without a size guard", {125}, {{"lints", "FINDS"}}},
        {"CXX-REPEAT", "std::views::repeat / repeat_view indexed without a size guard", {125}, {{"lints", "FINDS"}}},
        {"CXX-TAKE", "std::views::take / take_view indexed without a size guard", {125}, {{"lints", "FINDS"}}},
        {"CXX-DROP", "std::views::drop / drop_view indexed without a size guard", {125}, {{"lints", "FINDS"}}},
        {"CXX-FILTER", "std::views::filter / filter_view indexed without a size guard", {125}, {{"lints", "FINDS"}}},
        {"CXX-TRANSFORM-VIEW", "std::views::transform / transform_view indexed without a size guard", {125}, {{"lints", "FINDS"}}},
        {"CXX-ELEMENTS", "std::views::elements / elements_view indexed without a size guard", {125}, {{"lints", "FINDS"}}},
        {"CXX-IOTA", "std::views::iota / iota_view indexed without a size guard", {125}, {{"lints", "FINDS"}}},
        {"CXX-TAKE-WHILE", "std::views::take_while / take_while_view indexed without a size guard", {125}, {{"lints", "FINDS"}}},
        {"CXX-DROP-WHILE", "std::views::drop_while / drop_while_view indexed without a size guard", {125}, {{"lints", "FINDS"}}},
        {"CXX-KEYS", "std::views::keys / keys_view indexed without a size guard", {125}, {{"lints", "FINDS"}}},
        {"CXX-VALUES", "std::views::values / values_view indexed without a size guard", {125}, {{"lints", "FINDS"}}},
        {"CXX-REVERSE-VIEW", "std::views::reverse / reverse_view indexed without a size guard", {125}, {{"lints", "FINDS"}}},
        {"CXX-COUNTED", "std::views::counted / counted_view indexed without a size guard", {125}, {{"lints", "FINDS"}}},
        {"MEM-MISMATCHED-FREE", "malloc/free vs new/delete mismatch", {762}, {{"lints", "FINDS"}}},
        {"MEM-PTR-ARITH", "pointer index without bound or null guard", {125, 787}, {{"lints", "FINDS"}}},
        {"FLOAT-UB", "division by floating zero literal", {369}, {{"lints", "FINDS"}}},
        {"EMPTY-TU", "translation unit parsed no functions", {}, {{"inventory", "FINDS"}}},
        {"PARSE-GAP", "code in braces the parser attributed to no function", {}, {{"inventory", "FINDS"}}},
        {"LTL-SAFETY", "LTL safety violation", {}, {{"ltl", "PROVES"}, {"strix", "PROVES"}}},
        {"FUNC-CONTRACT", "ensures clause fails", {}, {{"bmc", "PROVES"}, {"dafny", "PROVES"}, {"wp", "PROVES"}, {"contracts", "PROVES"}, {"rapid", "FINDS"}, {"muttest", "SOME"}, {"llm", "READS"}}},
        {"INTENT", "comment/code contract mismatch", {}, {{"lints", "FINDS"}, {"llm", "READS"}}},
        {"INFOLEAK-PAD", "struct padding copied without zero-init", {200}, {{"lints", "FINDS"}}},
        {"API-PRECONDITION", "documented precondition unchecked in body", {}, {{"lints", "FINDS"}, {"llm", "READS"}}},
        {"TRUST-UNVALIDATED-INPUT", "parsed input used without range check", {20, 1284}, {{"lints", "FINDS"}, {"taint", "SOME"}}},
        {"CRYPTO-MISUSE", "rand() used as cryptographic key material", {330, 338}, {{"lints", "FINDS"}}},
        {"CRYPTO-SRAND", "srand(time()) seeds PRNG from clock", {330}, {{"lints", "FINDS"}}},
        {"TAINT-SINK", "untrusted input reaches dangerous sink", {78, 134}, {{"taint", "FINDS"}}},
        {"RACE-SHARED", "unsynchronized write to shared global", {362, 366}, {{"thread", "FINDS"}}},
        {"SYNTAX-ERROR", "source does not parse", {}, {{"polyglot", "FINDS"}}},
        {"TYPE-ERROR", "static type error", {}, {{"polyglot", "FINDS"}}},
        {"LANG-LINT", "language linter diagnostic", {}, {{"polyglot", "FINDS"}}},
        {"VCS-CONFLICT-MARKER", "unresolved merge conflict marker", {}, {{"polyglot", "FINDS"}}},
        {"SECRET-PRIVATE-KEY", "private key committed in source", {321}, {{"polyglot", "FINDS"}}},
        {"SECRET-AWS-KEY", "AWS access key committed in source", {798}, {{"polyglot", "FINDS"}}},
        {"SECRET-GITHUB-TOKEN", "GitHub token committed in source", {798}, {{"polyglot", "FINDS"}}},
        {"SECRET-SLACK-TOKEN", "Slack token committed in source", {798}, {{"polyglot", "FINDS"}}},
        {"SECRET-GOOGLE-API-KEY", "Google API key committed in source", {798}, {{"polyglot", "FINDS"}}},
        {"SECRET-STRIPE-KEY", "Stripe live key committed in source", {798}, {{"polyglot", "FINDS"}}},
    };
    return C;
}

std::vector<TaxonomyRow> coverage_from_report(const RunReport& report) {
    const auto PROVES = std::string(laws::STRENGTH_PROVES);
    const auto FINDS = std::string(laws::STRENGTH_FINDS);
    const auto SOME = std::string(laws::STRENGTH_SOME);
    const auto READS = std::string(laws::STRENGTH_READS);
    std::map<std::string, int> rank{{PROVES, 3}, {FINDS, 2}, {SOME, 1}, {READS, 1}};
    std::map<std::string, std::string> hits;
    std::set<std::string> ran_ok;
    bool bmc_closed = false;
    for (auto& s : report.stages) if (s.status == "ok") ran_ok.insert(s.name);
    auto note = [&](const std::string& cls, const std::string& strength) {
        if (cls.empty() || !rank.contains(strength)) return;
        // Python engine coverage_from_report.note: READS never overwrites an existing hit.
        if (strength == READS) {
            if (!hits.contains(cls)) hits[cls] = READS;
            return;
        }
        auto it = hits.find(cls);
        if (it == hits.end() || rank[strength] > rank[it->second]) hits[cls] = strength;
    };
    for (auto& s : report.stages) {
        for (auto& f : s.findings) {
            // LLM stage is READS only — never COVERED, even if the model names a class.
            if (s.name == "llm" || f.status == laws::HYPOTHESIS || f.status == laws::READS) {
                note(f.cls.empty() ? "INTENT" : f.cls, READS);
                continue;
            }
            if (f.status == laws::ERROR && !f.cls.empty() && f.strength == FINDS) { note(f.cls, FINDS); continue; }
            if (f.status == laws::NOTRUN || f.status == laws::CLEAN || f.status == laws::ERROR ||
                f.status == laws::NEEDS_HARNESS || f.status == laws::TIMEOUT ||
                f.status == laws::UNKNOWN || f.status == laws::NOSEED) continue;
            if (f.status == laws::PROVED || f.status == laws::PROVED_UNBOUNDED || f.status == laws::PROVED_ASSUMING) {
                // WP/contracts stay PROVED-ASSUMING; only BMC folds encoded UB.
                if (s.name == "bmc") bmc_closed = true;
                std::string cls = f.cls;
                if (cls.empty() && (s.name == "wp" || s.name == "contracts")) cls = "FUNC-CONTRACT";
                note(cls, f.strength.empty() ? PROVES : f.strength);
                continue;
            }
            if (f.status == laws::FAILED || f.status == laws::CRASH || f.status == laws::BOUNDED) {
                auto st = rank.contains(f.strength) ? f.strength : FINDS;
                if (f.status == laws::BOUNDED) st = SOME;
                // READS stays PARTIAL — never promote to FINDS/COVERED (the Python engine taxonomy.py).
                note(f.cls, st);
            }
        }
    }
    if (bmc_closed) {
        for (auto* id : {"INT-DIV-ZERO", "INT-SHIFT-UB", "INT-SIGNED-OVF", "MEM-OOB-READ", "MEM-OOB-WRITE"})
            if (!hits.contains(id)) hits[id] = PROVES;
    }
    std::vector<TaxonomyRow> rows;
    for (auto& c : taxonomy_classes()) {
        TaxonomyRow r; r.id = c.id; r.name = c.name; r.cwe = c.cwe; r.seen = c.seen;
        r.best = hits.contains(c.id) ? hits[c.id] : "";
        if (r.best == PROVES || r.best == FINDS) r.verdict = "COVERED";
        else if (r.best == SOME || r.best == READS) r.verdict = "PARTIAL";
        else {
            bool capable = false;
            bool any_reads = false;
            bool all_reads = true;
            int ncap = 0;
            for (auto& [inst, how] : c.seen) {
                if (!ran_ok.contains(inst)) continue;
                capable = true;
                ++ncap;
                if (how == READS) any_reads = true;
                else all_reads = false;
            }
            if (capable && any_reads && all_reads && ncap > 0) {
                r.best = READS;
                r.verdict = "PARTIAL";
            } else if (capable) {
                r.verdict = "PARTIAL";
                if (r.best.empty()) r.best = SOME;
            } else {
                r.verdict = "GAP";
            }
        }
        rows.push_back(std::move(r));
    }
    return rows;
}

bool only_llm_hits(const RunReport& report, const std::string& cid) {
    bool saw = false;
    for (auto& s : report.stages) {
        for (auto& f : s.findings) {
            if ((f.cls.empty() ? std::string() : f.cls) != cid) continue;
            if (f.status == laws::NOTRUN || f.status == laws::CLEAN || f.status == laws::ERROR ||
                f.status == laws::TIMEOUT || f.status == laws::UNKNOWN ||
                f.status == laws::NEEDS_HARNESS || f.status == laws::NOSEED)
                continue;
            saw = true;
            if (s.name != "llm" && f.status != laws::HYPOTHESIS && f.status != laws::READS)
                return false;
        }
    }
    return saw;
}

std::string refuse_llm_cover(const RunReport& report, const std::string& cid, std::string verdict,
                             const std::string& best) {
    if (verdict != "COVERED") return verdict;
    if (best == laws::STRENGTH_READS || best == laws::READS) return "PARTIAL";
    if (only_llm_hits(report, cid)) return "PARTIAL";
    return verdict;
}

}  // namespace prism
